### PR TITLE
Travis: Add LLVM 5.0

### PR DESCRIPTION
**Pull request by JohanEngelen**
LLVM 5.0 was just released.

### CODE REVIEW

**Comment by kinke** [comment]
There's still no prebuilt archive for Debian x64, they gotta be kidding.

**Comment by JohanEngelen** [comment]
Ubuntu x64 is there, just the filename is following a different pattern :/

**Comment by JohanEngelen** [comment]
Perhaps the LLVM binaries are a strange build. The `-dwarf-version` option is not supposed to be in the LLVM libs that we link with...?

**Comment by kinke** [comment]
You're most likely building with LLD, right? LLD 5.0+ needs #2148.

**Comment by JohanEngelen** [comment]
Ah, yes it's building with LLD.

**Pull request merged**
