### PR TITLE
Jit asm printer fixes and minor cleanups

### PR DESCRIPTION
**Pull request by Hardcode84**
Should fix `asm_output` issue on arm (#2687 )

### CODE REVIEW

**Comment by kinke** [comment]
I gave it a try:
```
/home/martin/ninja-ldc/bin/ldc2 -enable-dynamic-compile -run /home/martin/ldc/tests/dynamiccompile/asm_output.d
1629: --
1629: Exit Code: 1
1629: 
1629: Command Output (stdout):
1629: --
1629: $ "/home/martin/ninja-ldc/bin/ldc2" "-enable-dynamic-compile" "-run" "/home/martin/ldc/tests/dynamiccompile/asm_output.d"
1629: # command output:
1629: ===========================================
1629: 	.text
1629: _D10asm_output3barFZi:
1629: 	mov	r0, #7
1629: 	bx	lr
1629: 
1629: _D10asm_output3bazFZi:
1629: 	mov	r0, #8
1629: 	bx	lr
1629: 
1629: _D10asm_output3fooFZi:
1629: 	movw	r0, _D10asm_output5valuei
1629: 	movt	r0, _D10asm_output5valuei
1629: 	ldr	r0, [r0]
1629: 	bx	lr
1629: 
1629: 
1629: ===========================================
1629: 
1629: # command stderr:
1629: core.exception.AssertError@/home/martin/ldc/tests/dynamiccompile/asm_output.d(49): Assertion failure
1629: ----------------
1629: ??:? object.Throwable.TraceInfo core.runtime.defaultTraceHandler(void*) [0x65573]
1629: ??:? [0x6c1e3]
1629: ??:? [0x56c8f]
1629: ??:? [0x4d17b]
1629: ??:? _Dmain [0x1feb3]
1629: Error: /tmp/lit_tmp_7jRuyd/asm_output-5a2b881-b4857a failed with status: 1
```

**Comment by Hardcode84** [comment]
@kinke thanks

Interestingly, yous output is different from buildbot.

What triple and llvm version is it?

**Comment by kinke** [comment]
The triple is `arm-none-linux-gnueabihf` (=> ARMv6), LLVM is v6.

**Comment by Hardcode84** [comment]
Should work now

**Pull request merged**
