### PR TITLE
Do not require gold plugin when linking with LLD

### PR DESCRIPTION
**Pull request by myfreeweb**
LLD supports plugin-style flags, but the plugin itself might not exist. (`getLTOGoldPluginPath` might fail)

(on FreeBSD, it exists in an LLVM-version-specific place like `/usr/local/llvm80/lib/LLVMgold.so`. that should probably be added as well, the plugin is just not required for LLD. LLD is the primary linker here, `/usr/bin/ld` is LLD on aarch64 and amd64.)

### CODE REVIEW

**Comment by myfreeweb** [comment]
hm, I wonder if lld on macos expects Darwin flags

**Comment by kinke** [comment]
I guess calling `addLTOGoldPluginFlags()` makes no sense for LLD in general, i.e., adding the other `-plugin-*` options.

**Comment by myfreeweb** [comment]
I said "LLD supports plugin-style flags" for a reason :)

https://github.com/llvm-mirror/lld/blob/beb1e40a02f8be0cb2c71d551d86f84d495d41e3/ELF/Options.td#L505-L521 ← it's real!

**Comment by JohanEngelen** [comment]
LGTM. Can we add a test for this some way, or are we happy with not testing it?

**Pull request merged**
