### PR TITLE
Raise min LLVM version to 3.9

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Certainly in favor of this.

To prevent complaints later: https://forum.dlang.org/post/bmsdqayozfuxvbuwklbu@forum.dlang.org

**Comment by kinke** [comment]
[I forgot to remove the FileCheck and llvm-profdata .cpp files, amended now.]

**Comment by kinke** [comment]
It cost me time to find a workaround in #2870, and more importantly, is a PITA for the debuginfo API changes taking place between 3.7 and 3.9, which required poor Syniurge to figure out the necessary adaptations in #2826.

**Comment by kinke** [comment]
So the plan is to merge this tomorrow (giving people one week to respond to the forum thread), then adapt & merge #2870 and #2826.

**Comment by Geod24** [comment]
DMD's BuildKite is broken and the logs seem to point to this PR.
Failing build: https://buildkite.com/dlang/dmd/builds/1916#7d52edc4-50c7-49ef-9daa-50d456217d55

Logs:
```
-- Looking for unistd.h - found
--
  | -- GDB 7.11.1 detected
  | CMake Error at tests/CMakeLists.txt:22 (include):
  | include could not find load file:
  |  
  | /usr/lib/llvm-3.8/lib/cmake/llvm/LLVMConfig.cmake
  | Call Stack (most recent call first):
  | tests/CMakeLists.txt:27 (get_host_arch)
  |  
  |  
  | -- LDC_HOST_ARCH:
  | -- Configuring incomplete, errors occurred!
  | See also "/var/lib/buildkite-agent/builds/buildkite-agent-03-1/dlang/dmd/build/ldc-developers-ldc/bootstrap/CMakeFiles/CMakeOutput.log".
  | See also "/var/lib/buildkite-agent/builds/buildkite-agent-03-1/dlang/dmd/build/ldc-developers-ldc/bootstrap/CMakeFiles/CMakeError.log".
  | 🚨 Error: The command exited with status 1
```

Looks like we're trying to use 3.8. See [this issue]() for more details.

**Comment by joakim-noah** [comment]
Looks like the CMake config still allows 3.7/8, needs to be updated.

**Comment by kinke** [comment]
Yeah, I grepped for `30{7,8,9}`, missing `3.7` [here](https://github.com/ldc-developers/ldc/blob/master/CMakeLists.txt#L27).
BuildKite still not allowing public logs access is a PITA, I don't have the credentials at hand here at work. I guess the build image is based on Ubuntu 16.04 with its LLVM 3.8.

**Comment by wilzbach** [comment]
> BuildKite still not allowing public logs access is a PITA

Yeah, but you can use:

User: dummy@dlang.io
Pw: dlangrocks

until they finally fix that.

**Pull request merged**
