### PR TITLE
AppVeyor fix: Clear ERRORLEVEL user variable

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Nice that you found a solution to the problem so quickly.

I forgot/didn't know that lit-tests fail on x86. That's bad. Looking in to it!

**Comment by kinke** [comment]
Nope, that sadly didn't fix it.

**Comment by JohanEngelen** [comment]
@kinke I hope that the lit tests pass on Windows x86 after https://github.com/ldc-developers/ldc/pull/1515  .

**Comment by kinke** [comment]
Perfect, I'll remove the buggy AppVeyor workaround then.

**Pull request closed without merging**
