### PR TITLE
Switch to a white list of archs wrt. -m32/-m64 in cc cmdlines

### PR DESCRIPTION
**Pull request by kinke**
According to the gcc 10.1 cmdline docs.

### CODE REVIEW

**Comment by kubo39** [comment]
Maybe it would be better to use `-mx32` for x86_64-unknown-linux-gnux32, not sure LDC supports this architecture.
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

**Comment by kubo39** [comment]
This works fine for me.

```console
$ ./build-ldc/bin/ldc2 --mtriple=riscv64-unknown-none-elf -mcpu=generic-rv64 \
  -mabi=lp64 -mattr=+m,+a,+c --gcc=./gcc/bin/riscv64-unknown-elf-gcc \
  -Xcc=-march=rv64imac -Xcc=-mabi=lp64 -g -betterC hello.d
$ spike pk hello
bbl loaded
Hello, World!
```

Full description: https://github.com/kubo39/ldc-riscv-hello

**Comment by kinke** [comment]
Nice. Is the `-mabi` option for LDC required? It's the first time I see it being used.

**Comment by kubo39** [comment]
Ahh, it's not needed. Only `-Xcc=-abi=lp64` is required.

**Pull request merged**
