### PR TITLE
Remove PassNameParser (may be breaking some command lines!)

### PR DESCRIPTION
**Pull request by redstar**
This PR removes the command line option which adds the pass names as additional
command line options. This code prevents compiling for AArch64 (since LLVM 3.7)
and ARM (since LLVM 3.8). Recommendation on LLVM list was to use the PassNameParser
only in test tools but not in a production compiler.

### CODE REVIEW

**Comment by redstar** [comment]
See http://forum.dlang.org/post/tlziomjsfptuevvpnrjh@forum.dlang.org

**Comment by redstar** [comment]
In general there are command line options which have the same name as the pass. This results in an error during runtime.

**Comment by smolt** [comment]
Once of the switches is `-arm-load-store-opt`.  Somehow llc exposes it to the command line without conflict.

**Comment by redstar** [comment]
@smolt: `-arm-load-store-opt` is a command line option (defined in lib/Target/ARM/ARMTargetMachine.cpp).
But there is a pass of the same name. The `PassNameParser` takes the name of the pass and generates an new option with the pass name at runtime. The offending pass is defined in lib/Target/ARM/ARMLoadStoreOptimizer.cpp.

**Comment by smolt** [comment]
Yeah, I was in that territory a couple months ago: https://github.com/smolt/llvm/commit/958404db5ce77c2843a04e2f6fd8e032b01b394c

I just needed to get work done so temporarily did the rename for the command line options.

But - I noticed that llc didn't seem to have the same problem.  `-arm-load-store-opt` is available as a command line option.

**Comment by smolt** [comment]
BTW - I am fetching your change to try it out.

**Comment by redstar** [comment]
`llc` does not use the `PassNameParser`. The option you see is the one added in ARMTargetMachine.cpp.
`opt` uses the `PassNameParser` but does not add the backend passes. Therefore there is no conflict.

**Comment by smolt** [comment]
Ah, I didn't look carefully at the option lists.  That fills in the missing piece for me.  And your change works fine for me.  My test is building against llvm 3.8, use an arm or aarch64 triple, and specify -O.  It would fail before with something like:
```
$ bin/ldc2 -mtriple=arm-linux-gnueabihf -O -c foo.d
ldc2: CommandLine Error: Option 'arm-load-store-opt' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
LGTM

**Comment by joakim-noah** [comment]
Verified that this PR fixes the issue on Android/ARM, thanks.

**Pull request merged**
