### PR TITLE
trying to figure the failure on AppVeyor for x86

### PR DESCRIPTION
**Pull request by rainers**
Please do not merge!

Is this how a phobos PR can be tested on the build servers?

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@rainers What I do to check a druntime/phobos change is: create a phobos branch and push it to LDC's (not your own) repository. Then create an LDC PR that changes the submodule pointer to that branch.

**Comment by rainers** [comment]
@JohanEngelen Yeah, I also considered this, but didn't want to pollute the main repository (even if only temporary, but with a chance to screw up badly deleting the branch ;-) ). Patching appveyor.yml to merge the phobos PR works for my use case, too.

**Comment by rainers** [comment]
I finally figured it out: this is a codegen bug of the 32-bit build of LDC caused by a codegen bug in dmd used to compile it. Here is a reduced test:
```
bool _testr(real x) { return x == 2147483646.5; }

unittest
{
    assert(_testr(int.max - 0.5));
}
```
Fortunately it is already fixed:https://github.com/dlang/dmd/pull/5650

I can imagine 3 solutions:
- use a newer dmd: as the fix is not released yet that means a nightly build
- build LDC with itself again before running the tests
- ditch the 32-bit build and use multilib building. To do this we have to patch the cmake generated files to use the proper compiler. A larger downside will probably be that the tests will run too long and cause timeouts if tests for both architectures are executed. Having multiple configurations as in 
https://github.com/ldc-developers/ldc/pull/1469 would be useful.

**Comment by JohanEngelen** [comment]
Great work figuring this out!

**Comment by JohanEngelen** [comment]
@rainers Green on AppVeyor! Ready to merge? (I think for now this is the best option out of the three)

**Comment by rainers** [comment]
> Green on AppVeyor! Ready to merge? (I think for now this is the best option out of the three)

Yes, readyto merge. I also think using a newer dmd is the simplest option, but nightlies might be unstable. We can later switch to the announced 2.071.1, the changelog also shows the bugfix included.

**Comment by JohanEngelen** [comment]
> We can later switch to the announced 2.071.1, the changelog also shows the bugfix included.

Excellent.

Again: great work! Awesome that all CI testers are green now.

**Comment by rainers** [comment]
> Awesome that all CI testers are green now.

Thanks. Now we have to make sure the build timeouts don't cause random failures ;-)

**Pull request merged**
