### PR TITLE
Add timetrace2txt tool for simple ftime-trace workflow.

### PR DESCRIPTION
**Pull request by JohanEngelen**
It's quite rudimentary, but works and improvements can always be made later ;-)

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Running into compilation problems of the tool, because it uses the host/bootstrap compiler to build the tool. Shouldn't we switch to building our tools with the just-built LDC ?

**Comment by JohanEngelen** [comment]
You can also view the tools as an extra testcase. Apparently LDC 1.24 cannot deal with getting `ulong` values from JSON. Pretty bad, but OK...

**Comment by JohanEngelen** [comment]
It's a bit disappointing how difficult it is to write such a simple tool using the standard library when multiple compiler versions are involved :'(

**Comment by JohanEngelen** [comment]
OK to get this in?

**Review by thewilsonator — APPROVED** [review]

**Comment by kinke** [comment]
Sure (haven't looked at it). Nice that you got it working for ~every compiler/Phobos. :+1:

**Pull request merged**
