### PR TITLE
Fix compilation with most recent LLVM 

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Why is the 4.0 OSX box missing pip?

**Comment by kinke** [comment]
Probably because of a new default OSX image since yesterday: https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

**Comment by kinke** [comment]
Looks good, but still needs a new SPIR-V LLVM, right?

**Comment by thewilsonator** [comment]
Released a new one.

**Comment by thewilsonator** [comment]
One `std.datetime.date` failed on the SPIR-V box.

**Pull request merged**
