### PR TITLE
[ltsmaster] Sync druntime

### PR DESCRIPTION
**Pull request by lionello**
Pull in druntime fixes:

- https://github.com/ldc-developers/druntime/pull/172
- https://github.com/ldc-developers/druntime/pull/159
- https://github.com/ldc-developers/druntime/pull/156

### CODE REVIEW

**Comment by kinke** [comment]
```
/Users/travis/build/ldc-developers/ldc/runtime/druntime/src/rt/sections_ldc.d(583): Error: @nogc function 'rt.sections_ldc.getTLSRange' cannot call non-@nogc function 'core.sys.osx.mach.dyld._dyld_image_count'
/Users/travis/build/ldc-developers/ldc/runtime/druntime/src/rt/sections_ldc.d(585): Error: @nogc function 'rt.sections_ldc.getTLSRange' cannot call non-@nogc function 'core.sys.osx.mach.dyld._dyld_get_image_header'
/Users/travis/build/ldc-developers/ldc/runtime/druntime/src/rt/sections_ldc.d(583): Error: 'core.sys.osx.mach.dyld._dyld_image_count' is not nothrow
/Users/travis/build/ldc-developers/ldc/runtime/druntime/src/rt/sections_ldc.d(585): Error: 'core.sys.osx.mach.dyld._dyld_get_image_header' is not nothrow
/Users/travis/build/ldc-developers/ldc/runtime/druntime/src/rt/sections_ldc.d(578): Error: function 'rt.sections_ldc.getTLSRange' is nothrow yet may throw
```

**Comment by JohanEngelen** [comment]
@lionello @thewilsonator To prevent merging broken things into druntime, please always open an LDC merge request like this _before_ merging druntime PRs such that you get CI testing. Now we get a dirty druntime commit history with fixups...

**Comment by kinke** [comment]
@JohanEngelen: Do you mind a force-push on the ltsmaster druntime branch?

**Comment by kinke** [comment]
Attempt to fix it: #3338. Blocked because 32-bit x86 support is lacking as well.

**Comment by JohanEngelen** [comment]
> @JohanEngelen: Do you mind a force-push on the ltsmaster druntime branch?

Ah indeed hmm, I guess because we never referenced to it from LDC master branch, it's not too bad to do that.

**Comment by lionello** [comment]
Closing because it's very stale :(

**Pull request closed without merging**
