### PR TITLE
Circle & AppVeyor: Upgrade to LDC-LLVM 6.0.1

### PR DESCRIPTION
**Pull request by kinke**
Incl. `__debug_line` Mach-O section hack.

### CODE REVIEW

**Comment by joakim-noah** [comment]
I'd like to get [this llvm patch for Android/AArch64](https://github.com/ldc-developers/ldc/issues/2153#issuecomment-397947656) into our 6.0.1 llvm release, but there's a slight chance it might require tweaking, as it could be causing the remaining GC issues listed there. I'll submit a pull for our llvm once I get that worked out, just letting you know so you don't release before I get that in.

**Comment by kinke** [comment]
The Mach-O section hack seems to work fine:
```
3062:  ... runnable/debug_info.d          -g -O ()!!! [DISABLED for LDC]
3062:  !!! runnable/debug_info.d          DISABLED but PASSES!
```

[The test cannot be enabled, as it would still fail for non-LDC-LLVM, e.g., Travis.]

> just letting you know so you don't release before I get that in.

Thanks; I won't wait forever though. ;)

We should also discuss whether we want to include more targets, at least for the x86[_64] builds. With MIPS being usable now AFAIK, I tend to just enabling all targets. I'll check the effect on the LDC executable file size.

**Comment by kinke** [comment]
On Win64, `ldc2.exe` (`RelWithDebInfo` CMake config, enabled LLVM/LDC assertions) increases by 24% (57 MB vs. 46 MB) when enabling all targets, which is more than I thought.

**Comment by joakim-noah** [comment]
Better to just include the targets for which we have some support, which is less than half of those listed.

**Comment by kinke** [comment]
I think so too; MIPS alone adds less than 2 MB.

> targets for which we have some support

That's where `-betterC` can come in handy; cross-compiling a hello-world with C printf etc. might just work for more exotic targets and so potentially enourage someone to attempt a port. That's why I preferred the `all` variant first, but I expected an increase of 10-15%.

**Comment by joakim-noah** [comment]
Forgot about betterC, is it as bad for the release build with assertions turned off?

**Comment by JohanEngelen** [comment]
Note that `all` doesn't include WebAssembly
(needs `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly`).

**Comment by kinke** [comment]
> is it as bad for the release build with assertions turned off?

I'll just guess so, not too interested in rebuilding LLVM twice to find out. ;)

> Note that all doesn't include WebAssembly

Yep, there's a bunch of excluded experimental targets, incl. RISCV, but good point, there appears to be interest. So shall we just add Mips and WebAssembly for 6.0.1?

**Comment by JohanEngelen** [comment]
> there appears to be interest

I think this is a good measure to decide on. If we've seen some interest/work on a certain target, then let's include it to ease things.

**Comment by kinke** [comment]
Alright, that'd translate to `-DLLVM_TARGETS_TO_BUILD=AArch64;ARM;Mips;MSP430;NVPTX;PowerPC;X86 -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=RISCV;WebAssembly` then. There's also code for SPARC and SystemZ in LDC, but I guess the benefit of a x86_64 cross compiler for those is pretty low.

**Comment by kinke** [comment]
Mach-O section hack now opt-out via (hidden) `-preserve-dwarf-line-section=false`; option only available if built with supporting LLVM.

**Pull request merged**
