### PR TITLE
Win64 ABI: pass 'this' before 'sret' for extern (C++)

### PR DESCRIPTION
**Pull request by kinke**
Fixes https://github.com/ldc-developers/ldc/issues/1156.

### CODE REVIEW

**Comment by kinke** [comment]
This gets `runnable/cppa.d` to work on Win64 (at least with `merge-2.068`) - except for a minor linking issue (public static extern(C++) function defined in both .cpp and .d source files) and an apparently wrong test for MSVC-based builds, verifying an apparent DMD ABI bug. ;)

**Comment by kinke** [comment]
Not sure what to do about `extern(D)`. Currently, I know of these diffs compared to the Win64 C calling convention:

* `extern (D)` uses a reversed arguments order because DMD does and some runtime functions depend on this
* we pass slices (dynamic arrays) as LL aggregate (i.e., in 2 registers) and not as normal 16-bytes struct (byref)
* we pass sret before this (with this PR, only for `extern (D)`)

Needless to say, the D docs mention something about the D calling convention basically matching C's on that system.

**Comment by yebblies** [comment]
> `extern (D)` uses a reversed arguments order because DMD does and some runtime functions depend on this

IMO we (all) should match the C calling convention argument order.  If we really need to keep the same argument for array ops we can just switch the parameter order around.

> we pass slices (dynamic arrays) as LL aggregate (i.e., in 2 registers) and not as normal 16-bytes struct (byref)

They should be passed the same as the equivalent struct, I think DMD does this...

> we pass sret before this (with this PR, only for extern (D))

I don't know about this.  The only thing I can think of is that it would be nice to set the parameter order so that a member function can be called via a function pointer with `this` passed as the last argument.  I guess putting sret before this means this will always be last, so it works?

**Comment by kinke** [comment]
> IMO we (all) should match the C calling convention argument order.

We've been saying this for years, right? ;) I tried it once, there's still a PR for LDC, druntime and Phobos, but then interesting bugs appeared, e.g., sorting a range would sort it in descending order. So there are definitely some runtime functions relying on Walter's favorite arguments order. ;)

> They should be passed the same as the equivalent struct, I think DMD does this...

@JohanEngelen had a go at this, but it's quite tedious as we'd need to apply the TargetABI rewrites to all runtime function calls as well. Well maybe it wouldn't be *that* bad, but I'm not keen on doing this in the near future. ;)

> I guess putting sret before this means this will always be last, so it works?

Well right now, on all non-Win64 platforms, LDC passes the optional `sret` pointer, then the optional `this` or context pointer, then the optional `_arguments` array and only then the explicit args in either reversed (non-variadic `extern (D)` functions only) or regular order. So `this` is either the first or 2nd argument (and only ever the last one if the function takes no parameters at all). For Visual C++, it's always the first arg.

**Pull request merged**
