### PR TITLE
lit tests: forward "CC" environment variable

### PR DESCRIPTION
**Pull request by JohanEngelen**
@klickverbot

### CODE REVIEW

**Comment by thewilsonator** [comment]
Is there any reason ldc's `-gcc` switch isn't up to it?

**Comment by JohanEngelen** [comment]
Thanks @klickverbot

**Comment by ThomasMader** [comment]
Would it be possible to backport this fix to the ltsmaster branch to get that fixed for the next lts version?

**Comment by kinke** [comment]
Yep, done.

**Pull request merged**
