### PR TITLE
DI: Don't emit explicit alignment for pointer types

### LINKED ISSUE #3864: ldc2 with -g flag fails to link on Apple M1 Pro (aarch64) with unaligned pointer
I removed everything I could think of:

```console
% cat testit.d
extern(C) void main() {}
% ldc2 -betterC testit.d
% ./testit              
% ldc2 -betterC -g testit.d
ld: warning: pointer not aligned at address 0x10000402D (anon + 45 from testit.o)
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
```

### PR DESCRIPTION
**Pull request by kinke**
As clang doesn't seem to either. This *might* fix #3864.

### CODE REVIEW

**Comment by thewilsonator** [comment]
cc @schveiguy

**Comment by schveiguy** [comment]
Thanks, I'll try and make this happen, I've never built ldc2 from source. Is there a CI-built version I can download?

**Comment by kinke** [comment]
> Is there a CI-built version

Yes, the Azure jobs publish artifacts that can be downloaded (hover => burger button appearing on the right-hand side): https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=3176&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by schveiguy** [comment]
Thanks. I tried it, same linker error:
```console
steves@MacBook-Pro testd % ~/Downloads/osx-arm64/ldc2-1c9ad89b-osx-arm64/bin/ldc2 -betterC -g testbadlink.d
ld: warning: pointer not aligned at address 0x100004032 (anon + 50 from testbadlink.o)
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
steves@MacBook-Pro testd % cat testbadlink.d
extern(C) void main() {}
```

Same with release version.

**Pull request merged**
