### PR TITLE
Fix issue #1608

### PR DESCRIPTION
**Pull request by kinke**
Not happy at all with this change, that whole `canSkipPostblit` logic seems quite fragile. It's determined in `visit(AssignExp*)`, passed to `DtoAssign()`, and exclusively used in `DtoArrayAssign()` (i.e., when assigning to a static/dynamic array).

### CODE REVIEW

**Comment by kinke** [comment]
Slices (dynamic arrays) always represent ranges of lvalues since they point to unowned memory. Is there ever a case where copying from a slice can be optimized to a blit, without postblit for the copied elements and without destroying the assigned-from right-hand-side elements? Figuring out whether it's legal to do so should be quite complex, so I doubt it's feasible and required.

**Comment by ZombineDev** [comment]
> Is there ever a case where copying from a slice can be optimized to a blit, without postblit for the copied elements

That should be when the array element type is a POD (Plain Old Data) type. Perhaps you can usr [this](https://github.com/dlang/dmd/blob/v2.071.1/src/aggregate.h#L171) to determine that.

> and without destroying the assigned-from right-hand-side elements? 

That would mean that the array elements were moved instead of copied. I think only `std.algorithm.mutation : move` does that. I am not aware of a case where the frontend would generate moves. Furthermore only owners should be allowed to move elements and since slices conceptually borrow elements I don't think computer would generate implicit moves. OTOH, dmd is known to move objects placed on thr stack, so if were talking for static arrays, I may be wrong

**Comment by kinke** [comment]
> Furthermore only owners should be allowed to move elements and since slices conceptually borrow elements I don't think the compiler would generate any moves.

Thanks, that's what I thought.
[We (LDC) obviously already have the POD optimization, I meant non-POD types only.]

**Comment by kinke** [comment]
Wrt. moving from a static array, here'd be an example for code that could possibly be moved, but shows the difficulties of analyzing this:

```D
int numPostblit = 0, numDtor = 0;

struct S
{
    int v;
    this(this) { ++numPostblit; }
    ~this() { ++numDtor; } }

void foo()
{
    S[4] sa = [ S(1), S(2), S(3), S(4) ];

    // helper to generate a slice rvalue
    static S[] toSlice(ref S[4] sa) { return sa[1..$]; }

    S[3] r = toSlice(sa); // elements 2,3,4 could possibly be moved as they'd be destructed
                          // immediately anyway as the owner `sa` goes out of scope
                          // element 1 would still need to be destructed as non-moved part of `sa`
}

void main()
{
    foo();
    assert(numPostblit == 3);
    assert(numDtor == 7);
}
```

The above passes with this PR and DMD 2.071; fails due to missing postblit for LDC head.

**Comment by kinke** [comment]
I tried to make the `DtoArrayAssign()` postblit behavior consistent with our manual `callPostblit()` calls for structs (e.g., by passing `canSkipPostblit = false` when we do a postblit for structs manually afterwards), but apparently there are cases where we must not do postblits for array elements but where they are required for structs. So this still feels fragile to me.

What remains is a fix for issue #1608 and a visit of all `DtoAssign()` call sites, where I replaced the TOKconstruct + canSkipPostblit combo by a semantically equivalent TOKblit. I also replaced assignments from DSliceValues to simple and intuitive stores (of the length+ptr pair).

**Comment by kinke** [comment]
Looking forward to see this fix in 1.1.

**Comment by kinke** [comment]
Löl that was quick. ;)

**Pull request merged**
