### PR TITLE
Cherrypick DMD PR #6582.

### PR DESCRIPTION
**Pull request by JohanEngelen**
Fix dlang Issue 17237 - Wrong alignment for 256-bit vectors.

https://forum.dlang.org/post/dehxjddmuyzoyqkbdzwn@forum.dlang.org
https://issues.dlang.org/show_bug.cgi?id=17237

### CODE REVIEW

**Comment by kinke** [comment]
Please wait before merging this, I asked Iain for more details upstream (https://github.com/dlang/dmd/pull/6582).

**Comment by kinke** [comment]
Looks like I messed up something when merging the front-end - we have 2 `Target::alignsize()` implementations (`ddmd/target.d` and `gen/target.cpp`), and no linker complains. :(

**Comment by JohanEngelen** [comment]
I thought to fully apply the diff, even if we don't use some code of it. But perhaps you prefer to not artificially add to the diff with the "based-upon dlang version"?

**Comment by JohanEngelen** [comment]
Fixed.

**Comment by JohanEngelen** [comment]
Ah lol. Confusion :)
I thought you wanted not the full diff. I have no preference, let me know.  I'll add the git commit hash too then.

**Pull request merged**
