### PR TITLE
[WIP] AppVeyor: Upgrade LLVM to 4.0.1

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
@majnemer: Hey, sorry for testing this too late, but apparently we hit a Win64 EH regression with LLVM 4.0 (`No open Win64 EH frame function!` in `MCStreamer::EnsureValidWinFrameInfo()`). If you have some time, [here](https://dl.dropboxusercontent.com/s/1y13igtdawu4pug/xtest46.zip?dl=0)'s the zipped (and optimized) .ll for which `llc` crashes.

**Comment by majnemer** [comment]
Reduced:
```
target datalayout = "e-m:w-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @__CxxFrameHandler3(...)

define void @f1() #1 personality i32 (...)* @__CxxFrameHandler3 {
  ret void
}

define void @f2() {
  ret void
}

attributes #1 = { nounwind }
```

Filed a LLVM PR: https://bugs.llvm.org/show_bug.cgi?id=32335

**Comment by kinke** [comment]
Thanks a lot, David.

**Comment by majnemer** [comment]
Reid fixed LLVM PR32335 in LLVM r298276

**Comment by kinke** [comment]
Thanks, will test it sometime soon.

**Comment by kinke** [comment]
I cherry-picked the @rnk fix onto release_40, all green here. Thanks!

**Comment by kinke** [comment]
Vanilla LLVM 4.0 error fixed by #2049. Unfortunately, another regression popped up, a unittest failure for `std.container.util` (release only) in [std.container.rbtree](https://github.com/ldc-developers/phobos/blob/ldc/std/container/rbtree.d#L1059).
Needs `-release` and `-O3` (works for all lower opt levels).

**Comment by kinke** [comment]
Rebased and expecting the above unittest to fail.

**Comment by kinke** [comment]
Reduced to this, failing consistently on Win64 with LLVM 4.0 in line 580 when compiled with `-O3 -release -unittest -main`:

```D
void foo()
{
    auto a = new RedBlackTree!(int, "a > b")(5);
    auto b = new RedBlackTree!(int)(4);
}

import std.functional : binaryFun;

struct RBNode(V)
{
    alias Node = RBNode*;

    private Node _left;
    private Node _right;
    private Node _parent;

    V value;

    enum Color : byte
    {
        Red,
        Black
    }

    Color color;

    @property inout(RBNode)* left() inout
    {
        return _left;
    }

    @property inout(RBNode)* right() inout
    {
        return _right;
    }

    @property inout(RBNode)* parent() inout
    {
        return _parent;
    }

    @property Node left(Node newNode)
    {
        _left = newNode;
        if (newNode !is null)
            newNode._parent = &this;
        return newNode;
    }

    @property Node right(Node newNode)
    {
        _right = newNode;
        if (newNode !is null)
            newNode._parent = &this;
        return newNode;
    }

    Node rotateR()
    {
        if (isLeftNode)
            parent.left = _left;
        else
            parent.right = _left;
        Node tmp = _left._right;

        _left.right = &this;

        left = tmp;

        return &this;
    }

    Node rotateL()
    {
        if (isLeftNode)
            parent.left = _right;
        else
            parent.right = _right;
        Node tmp = _right._left;

        _right.left = &this;

        right = tmp;
        return &this;
    }


    @property bool isLeftNode() const
    {
        return _parent._left is &this;
    }

    void setColor(Node end)
    {
        if (_parent !is end)
        {
            if (_parent.color == Color.Red)
            {
                Node cur = &this;
                while (true)
                {
                    if (cur._parent.isLeftNode)
                    {
                        Node y = cur._parent._parent._right;
                        if (y !is null && y.color == Color.Red)
                        {
                            cur._parent.color = Color.Black;
                            y.color = Color.Black;
                            cur = cur._parent._parent;
                            if (cur._parent is end)
                            {
                                cur.color = Color.Black;
                                break;
                            }
                            else
                            {
                                cur.color = Color.Red;
                                if (cur._parent.color == Color.Black)
                                    break;
                            }
                        }
                        else
                        {
                            if (!cur.isLeftNode)
                                cur = cur._parent.rotateL();
                            cur._parent.color = Color.Black;
                            cur = cur._parent._parent.rotateR();
                            cur.color = Color.Red;
                            break;
                        }
                    }
                    else
                    {
                        Node y = cur._parent._parent._left;
                        if (y !is null && y.color == Color.Red)
                        {
                            cur._parent.color = Color.Black;
                            y.color = Color.Black;
                            cur = cur._parent._parent;
                            if (cur._parent is end)
                            {
                                cur.color = Color.Black;
                                break;
                            }
                            else
                            {
                                cur.color = Color.Red;
                                if (cur._parent.color == Color.Black)
                                    break;
                            }
                        }
                        else
                        {
                            if (cur.isLeftNode)
                                cur = cur._parent.rotateR();
                            cur._parent.color = Color.Black;
                            cur = cur._parent._parent.rotateL();
                            cur.color = Color.Red;
                            break;
                        }
                    }
                }

            }
        }
        else
        {
            color = Color.Black;
        }
    }

    Node remove(Node end)
    {
        Node x;
        Node ret = next;

        if (_left !is null && _right !is null)
        {
            Node yp, yl, yr;
            Node y = ret; // y = next
            yp = y._parent;
            yl = y._left;
            yr = y._right;
            auto yc = y.color;
            auto isyleft = y.isLeftNode;

            if (isLeftNode)
                _parent.left = y;
            else
                _parent.right = y;
            y.left = _left;
            if (_right is y)
                y.right = &this;
            else
                y.right = _right;
            y.color = color;

            left = yl;
            right = yr;
            if (_parent !is y)
            {
                if (isyleft)
                    yp.left = &this;
                else
                    yp.right = &this;
            }
            color = yc;
        }

        if (_left !is null)
            x = _left;
        else
            x = _right;

        bool deferedUnlink = false;
        if (x is null)
        {
            x = &this;
            deferedUnlink = true;
        }
        else if (isLeftNode)
            _parent.left = x;
        else
            _parent.right = x;

        if (color == color.Black)
        {
            while (x._parent !is end && x.color == Node.Color.Black)
            {
                if (x.isLeftNode)
                {
                    Node w = x._parent._right;
                    if (w.color == Node.Color.Red)
                    {
                        w.color = Node.Color.Black;
                        x._parent.color = Node.Color.Red;
                        x._parent.rotateL();
                        w = x._parent._right;
                    }
                    Node wl = w.left;
                    Node wr = w.right;
                    if ((wl is null || wl.color == Node.Color.Black) &&
                            (wr is null || wr.color == Node.Color.Black))
                    {
                        w.color = Node.Color.Red;
                        x = x._parent;
                    }
                    else
                    {
                        if (wr is null || wr.color == Node.Color.Black)
                        {
                            wl.color = Node.Color.Black;
                            w.color = Node.Color.Red;
                            w.rotateR();
                            w = x._parent._right;
                        }

                        w.color = x._parent.color;
                        x._parent.color = Node.Color.Black;
                        w._right.color = Node.Color.Black;
                        x._parent.rotateL();
                        x = end.left; // x = root
                    }
                }
                else
                {
                    Node w = x._parent._left;
                    if (w.color == Node.Color.Red)
                    {
                        w.color = Node.Color.Black;
                        x._parent.color = Node.Color.Red;
                        x._parent.rotateR();
                        w = x._parent._left;
                    }
                    Node wl = w.left;
                    Node wr = w.right;
                    if ((wl is null || wl.color == Node.Color.Black) &&
                            (wr is null || wr.color == Node.Color.Black))
                    {
                        w.color = Node.Color.Red;
                        x = x._parent;
                    }
                    else
                    {
                        if (wl is null || wl.color == Node.Color.Black)
                        {
                            wr.color = Node.Color.Black;
                            w.color = Node.Color.Red;
                            w.rotateL();
                            w = x._parent._left;
                        }

                        w.color = x._parent.color;
                        x._parent.color = Node.Color.Black;
                        w._left.color = Node.Color.Black;
                        x._parent.rotateR();
                        x = end.left; // x = root
                    }
                }
            }
            x.color = Node.Color.Black;
        }

        if (deferedUnlink)
        {
            if (isLeftNode)
                _parent.left = null;
            else
                _parent.right = null;
        }

        _left = _right = _parent = null;

        return ret;
    }

    @property inout(RBNode)* leftmost() inout
    {
        inout(RBNode)* result = &this;
        while (result._left !is null)
            result = result._left;
        return result;
    }

    @property inout(RBNode)* rightmost() inout
    {
        inout(RBNode)* result = &this;
        while (result._right !is null)
            result = result._right;
        return result;
    }

    @property inout(RBNode)* next() inout
    {
        inout(RBNode)* n = &this;
        if (n.right is null)
        {
            while (!n.isLeftNode)
                n = n._parent;
            return n._parent;
        }
        else
            return n.right.leftmost;
    }

    @property inout(RBNode)* prev() inout
    {
        inout(RBNode)* n = &this;
        if (n.left is null)
        {
            while (n.isLeftNode)
                n = n._parent;
            return n._parent;
        }
        else
            return n.left.rightmost;
    }

    Node dup(scope Node delegate(V v) alloc)
    {
        Node copy = alloc(value);
        copy.color = color;
        if (_left !is null)
            copy.left = _left.dup(alloc);
        if (_right !is null)
            copy.right = _right.dup(alloc);
        return copy;
    }

    Node dup()
    {
        Node copy = new RBNode!V;
        copy.value = value;
        copy.color = color;
        if (_left !is null)
            copy.left = _left.dup();
        if (_right !is null)
            copy.right = _right.dup();
        return copy;
    }
}

private struct RBRange(N)
{
    alias Node = N;
    alias Elem = typeof(Node.value);

    private Node _begin;
    private Node _end;

    private this(Node b, Node e)
    {
        _begin = b;
        _end = e;
    }

    @property bool empty() const
    {
        return _begin is _end;
    }

    @property Elem front()
    {
        return _begin.value;
    }

    @property Elem back()
    {
        return _end.prev.value;
    }

    void popFront()
    {
        _begin = _begin.next;
    }

    void popBack()
    {
        _end = _end.prev;
    }

    @property RBRange save()
    {
        return this;
    }
}

final class RedBlackTree(T, alias less = "a < b", bool allowDuplicates = false)
    if (is(typeof(binaryFun!less(T.init, T.init))))
{
    alias _less = binaryFun!less;

    alias Elem = T;

    private alias RBNode = .RBNode!Elem;
    private alias Node = RBNode.Node;

    private Node   _end;
    private Node   _begin;
    private size_t _length;

    private void _setup()
    {
        assert(!_end); //Make sure that _setup isn't run more than once.
        _begin = _end = allocate();
    }

    static private Node allocate()
    {
        return new RBNode;
    }

    static private Node allocate(Elem v)
    {
        auto result = allocate();
        result.value = v;
        return result;
    }

    alias Range = RBRange!(RBNode*);

    private inout(RBNode)* _find(Elem e) inout
    {
        static if (allowDuplicates)
        {
            inout(RBNode)* cur = _end.left;
            inout(RBNode)* result = null;
            while (cur)
            {
                if (_less(cur.value, e))
                    cur = cur.right;
                else if (_less(e, cur.value))
                    cur = cur.left;
                else
                {
                    // want to find the left-most element
                    result = cur;
                    cur = cur.left;
                }
            }
            return result;
        }
        else
        {
            inout(RBNode)* cur = _end.left;
            while (cur)
            {
                if (_less(cur.value, e))
                    cur = cur.right;
                else if (_less(e, cur.value))
                    cur = cur.left;
                else
                    return cur;
            }
            return null;
        }
    }

    private auto _add(Elem n)
    {
        Node result;
        static if (!allowDuplicates)
            bool added = true;

        if (!_end.left)
        {
            _end.left = _begin = result = allocate(n);
        }
        else
        {
            Node newParent = _end.left;
            Node nxt;
            while (true)
            {
                if (_less(n, newParent.value))
                {
                    nxt = newParent.left;
                    if (nxt is null)
                    {
                        newParent.left = result = allocate(n);
                        break;
                    }
                }
                else
                {
                    static if (!allowDuplicates)
                    {
                        if (!_less(newParent.value, n))
                        {
                            result = newParent;
                            added = false;
                            break;
                        }
                    }
                    nxt = newParent.right;
                    if (nxt is null)
                    {
                        newParent.right = result = allocate(n);
                        break;
                    }
                }
                newParent = nxt;
            }
            if (_begin.left)
                _begin = _begin.left;
        }

        static if (allowDuplicates)
        {
            result.setColor(_end);
            ++_length;
            return result;
        }
        else
        {
            import std.typecons : Tuple;

            if (added)
            {
                ++_length;
                result.setColor(_end);
            }
            return Tuple!(bool, "added", Node, "n")(added, result);
        }
    }

    Range opSlice()
    {
        return Range(_begin, _end);
    }

    bool opBinaryRight(string op)(Elem e) const if (op == "in")
    {
        return _find(e) !is null;
    }

    @safe pure unittest
    {
        auto ts = new RedBlackTree(1, 2, 3, 4, 5);
        assert(cast(Elem)3 in ts);
        assert(cast(Elem)6 !in ts);
    }

    size_t stableInsert(Stuff)(Stuff stuff)
    {
        size_t result = 0;
        static if (allowDuplicates)
        {
            foreach (e; stuff)
            {
                ++result;
                _add(e);
            }
        }
        else
        {
            foreach (e; stuff)
            {
                if (_add(e).added)
                    ++result;
            }
        }
        return result;
    }

    this(Elem[] elems...)
    {
        _setup();
        stableInsert(elems);
    }
}
```

It works when specifying the `T` type parameter for the `RedBlackTree` template in line 579 (`RedBlackTree` => `RedBlackTree!T`); specifying it explicitly also shrinks down the produced .ll by 5 KB. Something strange going on here...

**Comment by kinke** [comment]
Stepping through the code, the following seems to happen:

* The module's unittest function contains inlined versions of the 2 unittests (for both instantiated `RedBlackTree!((int a, int b) => a > b)` and `RedBlackTree!((int a, int b) => a < b)` templates).
* It loads the 5 ints from the global only once at the beginning (and the first 4 ints are loaded into the XMM6 register in asm).
* For some reason, inbetween the 2 unittests, it executes an `std.format:847` unittest. Now in there, there's an assert making sure that a `FormatException` is thrown. When continuing from there, XMM6 is reset to zeros.
* The 2nd unittest still assumes the first 4 ints are in XMM6. This explains the output with the first 4 elements being zero.

**Comment by kinke** [comment]
Yep, when commenting out the throwing line in the [std.format unittest](https://github.com/ldc-developers/phobos/blob/ldc/std/format.d#L877-L878), XMM6 is restored correctly when leaving the non-inlined unittest function.

**Comment by rnk** [comment]
Here is a C++ program that exhibits the same bug:

```
$ cat a.cpp
double get_csr(double);
void throw_internally();
void use_csr(double d);
int main() {
  double csr = get_csr(1.5);
  throw_internally();
  use_csr(csr);
}

$ cat b.cpp
extern "C" int printf(const char *, ...);
void use_csr(double d) {
  printf("%f\n", d);
}
double __declspec(noinline) get_csr(double d) {
  asm volatile("" : "=r"(d) : "0"(d));
  return d;
}
void throw_internally() {
  double csr = get_csr(0.0);
  use_csr(csr);
  use_csr(csr);
  try {
    throw 42;
  } catch (...) {
  }
}

$ clang-cl -EHsc -O0 a.cpp b.cpp -Fet.exe && ./t.exe
0.000000
0.000000
1.500000

$ clang-cl -EHsc -O2 a.cpp b.cpp -Fet.exe && ./t.exe
0.000000
0.000000
0.000000  # BUG
```

**Comment by rnk** [comment]
I filed https://bugs.llvm.org/show_bug.cgi?id=32507 for this.

**Comment by kinke** [comment]
Oh much obliged, @rnk! :+1:

**Comment by kinke** [comment]
Although the LLVM issue hasn't been updated, the `std.container.rbtree` failure seems to have disappeared with current LDC master and LLVM 4.0.1 on Win64.

**Comment by kinke** [comment]
Another annoying issue: the test runner executables aren't relinked if they exist and their tested lib has been updated (due to a changed src module etc.). They are currently linked in manually via linker flags (pull in all objects...) and the build dependency is added via `add_dependencies()`...

**Pull request merged**
