### PR TITLE
[cmake] Allow specification of D_COMPILER on CMake cmdline.

### PR DESCRIPTION
**Pull request by JohanEngelen**
Use with `cmake -DD_COMPILER=ldmd2`. Resolves issue #1320

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Thanks for testing.

**Comment by JohanEngelen** [comment]
@klickverbot  Marked it as WIP for now.

**Comment by kinke** [comment]
It'd be a trivial fix for AppVeyor - don't set the env variable ([here](https://github.com/ldc-developers/ldc/blob/master/appveyor.yml#L73)) and set the CMake variable in the CMake command line instead.

**Comment by JohanEngelen** [comment]
I want both the environment variable DMD and the CMake variable D_COMPILER to work. D_COMPILER has priority over environment variable DMD.

I think it should be fixed now. Let's see what the tester machines say.

**Comment by JohanEngelen** [comment]
Great! (virtually) Green on all now!

**Pull request merged**
