### PR TITLE
[ltsmaster] MinGW fixes

### PR DESCRIPTION
**Pull request by kinke**
This gets ltsmaster to build and the druntime/Phobos unittest runners to link (i.e., no missing symbols) on Win64 using recent [MSYS2](http://www.msys2.org/) incl. its prebuilt

* `cmake` (3.6.2)
* `make` (4.2.1)
* `mingw-w64-x86_64-gcc` (7.2)
* `mingw-w64-x86_64-llvm` (5.0.0)
* `mingw-w64-x86_64-libconfig` (1.5)
* `mingw-w64-x86_64-dlfcn` (1.1.1)

[Use `pacman -S <name>` to install a package in the MSYS shell.]
Exemplary CMake command-line (yes, somehow `CXX=g++` and `-DWIN32=ON` were necessary in my case):
```
CC=gcc CXX=g++ cmake -DWIN32=ON -DLLVM_ROOT_DIR=/mingw64/ \
    -DCMAKE_INSTALL_PREFIX=/c/ldc/mingw-x64 -DCMAKE_BUILD_TYPE=Release ../ldc
```

Afterwards, the `ldc2.conf` config file needs to be patched manually, converting the MSYS paths to normal ones: `/c/ldc/...` => `c:/ldc/...`. The produced binaries then immediately crash at startup when running the module ctors:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000053b61e in rt.lifetime.__getBlkInfo(void*) ()
(gdb) bt
#0  0x000000000053b61e in rt.lifetime.__getBlkInfo(void*) ()
#1  0x000000000053f524 in _d_arrayappendcTX ()
#2  0x000000000053f3ad in _d_arrayappendT ()
#3  0x0000000000551da3 in core.sys.windows.stacktrace.generateSearchPath() ()
#4  0x0000000000551ecc in core.sys.windows.stacktrace._sharedStaticCtor2() ()
#5  0x0000000000542708 in rt.minfo.runModuleFuncs!(rt.minfo.ModuleGroup.runCtors().__lambda2).runModuleFuncs(const(immutable(object.ModuleInfo)*)[]) ()
#6  0x000000000054257c in rt.minfo.ModuleGroup.runCtors() ()
#7  0x0000000000542dd0 in rt.minfo.rt_moduleCtor().__foreachbody1(ref rt.sections_ldc.SectionGroup) ()
#8  0x00000000005440a8 in rt.sections_ldc.SectionGroup.opApply(scope int(ref rt.sections_ldc.SectionGroup) delegate) ()
#9  0x0000000000542d93 in rt_moduleCtor ()
#10 0x0000000000539075 in rt_init ()
#11 0x0000000000539dde in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll() ()
#12 0x0000000000539d6e in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).tryExec(scope void() delegate) ()
#13 0x0000000000539cae in _d_run_main ()
#14 0x000000000040ea32 in main ()
```

### CODE REVIEW

**Comment by kinke** [comment]
Pinging @wirx6.

**Comment by kinke** [comment]
Oh and `ldmd2` fails to locate the `ldc2` executable.

**Comment by wirx6** [comment]
64-bit package+PKGBUILD
[mingw-w64-ldc.zip](https://github.com/ldc-developers/ldc/files/1423552/mingw-w64-ldc.zip)
- `/mingw64/etc/ldc2.conf` need to be patched manually
- runtime built with flag `-d-debug=PRINTF`
- used c++ compiler: clang++
- llvm version: 5.0.0
- latest commit: 684de77
- only for testing

**Comment by kinke** [comment]
The reason for the crash appears to be that the TLS global `rt.lifetime.__nextBlkIdx` isn't initialized with 0, but some random value.

**Pull request merged**
