### PR TITLE
Convert to monorepo, including druntime and dmd-testsuite directly

### PR DESCRIPTION
**Pull request by kinke**
Based on the DMD-git-rewrite script in https://github.com/ldc-developers/ldc/pull/4274.

### CODE REVIEW

**Comment by kinke** [comment]
The fat merge commit was performed via: `git merge -s recursive -X ours --allow-unrelated-histories dmd-rewrite-first-merged-dmd-druntime-with-ldc-druntime-patches`. This kept our versions of files under `dmd/`.

I've diffed the trees (current master and the new monorepo) 2 times manually via `meld` and checked extra/missing/modified files, all looking good.

Mainly checking CI here and giving you some time for feedback. I'll merge this manually into `master` (fast-forward merge), and then also push the `pre-monorepo` tag for previous master and all the new `dmd-rewrite-*` tags plus the `dmd-rewrite-{master,stable}` branches.

So keeping LDC master frozen before I have your okays would be appreciated.

**Comment by JohanEngelen** [comment]
I can't test what it looks like, I get a git error when I follow github's instructions to merge this PR:
```
> git merge origin/monorepo
Updating 05fb6d5aca..5c3478c129
error: The following untracked working tree files would be overwritten by merge:
	runtime/druntime/posix.mak
	runtime/druntime/src/__builtins.di
	runtime/druntime/src/core/atomic.d
	runtime/druntime/src/core/attribute.d
	runtime/druntime/src/core/bitop.d
	runtime/druntime/src/core/builtins.d
```
Do you know how to fix that error?

**Comment by kinke** [comment]
I wouldn't try to *merge* it, but to just check it out (`git checkout -f monorepo` - `-f` should make it quietly replace the checked-out submodules with the new in-tree files), or simply browse it here on GitHub: https://github.com/ldc-developers/ldc/tree/monorepo

I've just checked the blame-history, that works fine for dmd-testsuite and druntime. For the DMD source files, it's currently limited to the existing history here and will slowly get the new post-DMD-monorepo pieces as they come.

**Comment by JohanEngelen** [comment]
> I'll merge this manually into `master` (fast-forward merge)

What did you mean with this? An actual `git merge` or something else?

**Comment by kinke** [comment]
Sure, an actual merge (without initialized submodules causing problems like yours), and making sure it's a fast-forward merge (=> master unchanged in the meantime). That closes this PR automatically without additional merge commit.

**Comment by kinke** [comment]
I've also just tested merging current DMD stable - simply awesome! :D
```
$ git checkout -b merge-2.101
$ git merge dmd-rewrite-stable
$ git status
…
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
	both modified:   dmd/attrib.d
	both modified:   dmd/dstruct.d
	both modified:   dmd/dsymbolsem.d
	deleted by them: tests/dmd/runnable/cstuff2.c
…
```

(Phobos still needs to be bumped as usual.)

**Comment by kinke** [comment]
I'll merge tomorrow (well, today - Friday) unless there are objections. @JohanEngelen @thewilsonator

**Comment by thewilsonator** [comment]
None from us. Thanks for the hard work

**Comment by kinke** [comment]
Oh that was quick, nice, might as well do it sooner. :) - The next sync might be a bit delicate due to in-place replacing the previous submodules with files, and I'm not sure whether `-f` etc. is a good idea, or whether we might end up losing the whole `.git` stuff for the submodules (unpushed branches, WIP stuff etc. etc.). I'll probably rename the `runtime/druntime` and `tests/dmd` dirs locally.

**Pull request merged**
