### PR TITLE
CI: Set up Azure Pipelines, drop AppVeyor, rededicate Circle

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
@ZombineDev: For Windows, the performance seems to very roughly match AppVeyor - 2 (logical?) cores, 3.5 GB RAM. But the max configurable time-out seems to be 6h, which should definitely eliminate all time-out issues. :)

**Comment by kinke** [comment]
Overall, I'm quite happy with it so far. It's not perfect, e.g., there's no ssh support, and a step's `displayName` comes after its script (which can be quite long). I also like the GUI. For Windows, all that's still needed is adding a multilib job (yes, one can define a job with dependencies on other jobs - so that it's run after both x64 and x86 jobs have succeeded, in order to create a merged multilib package) and uploading the packages to GitHub (incl. how to figure out if the build is a PR/a commit on the master branch/a tagged commit). Then we don't need AppVeyor anymore. Our LLVM fork can/should be migrated too, as AppVeyor has lately always been too slow to build the LLVM packages in 1h (so that I had to build the 4 packages manually, getting on my nerves).

We could also replace CircleCI (Linux & macOS) with this and use the Azure Pipelines for all x86/x64 packages (and Shippable for the AArch64 one). We'd only use 5 jobs per commit then (Windows x86 & x64 & tiny multilib, Linux multilib, macOS x64), so that 2 commits can be tested in parallel (10 free concurrent jobs).

**Comment by kinke** [comment]
Current status:

* Package upload to GitHub is still to be tested, as is the package generation for tagged builds (LLVM with disabled assertions, package filename, package root dir name).
* Windows: should be fine, incl. additional tests compared to AppVeyor (dynamic compile integration test, multilib smoke tests). Untagged builds use LLVM with enabled assertions again.
* macOS:
  * v10.13 (Circle: 10.12) and default Xcode 9.4.1 (multiple Xcode versions preinstalled, incl. v10; Circle: v9.2). The issue worked around in #2839 for Travis thus strikes again, `druntime-test-shared` fails. @JohanEngelen, @dnadlinger: someone of you Mac guys please consider debugging, as I guess your system would match that setup. Maybe related to https://forum.dlang.org/thread/q0l0t6$2mnn$1@digitalmars.com and/or #2820.
  * **x64 only**, no multilib package with fat libs anymore.
  * FIXME: lit isn't found.
  * Should we raise `MACOSX_DEPLOYMENT_TARGET` from 10.8 to 10.9 while at it (incl. our LLVM fork), to get rid of `clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]`?
* Linux:
  * Ubuntu 16.04 (Circle: 14.04) and default gcc 5.4.0 (Circle: backported 6.5.0). The LLVM prebuilt by Circle doesn't work for linking, apparently due to C++ ABI mismatch. I'll thus have to switch our LLVM fork to Azure first; probably with LLVM 8.0.

**Comment by kinke** [comment]
I rededicated CircleCI: no self-compilation & packaging anymore, also combining bits from Semaphore and Travis.

* Linux
  * Ubuntu 18.04: using distro gcc (7.3) + LLVM (6.0) + compiler-rt libs, multilib, druntime sanitizers support
  * Ubuntu rolling (latest, currently 18.10): using distro gcc (8.2) + LLVM (7.0) + compiler-rt libs, multilib, shared druntime/Phobos libs only (=> running lit-tests & DMD testsuite with shared libs, previously only tested by Travis)
* macOS: using our prebuilt LLVM 7.0.1 with enabled assertions, x64 only
  * static+shared libs
  * shared libs only

**Comment by kinke** [comment]
Alright, looks like we're pretty much set for LLVM 8 (from yesterday), incl. Khronos SPIRV-LLVM-Translator as git submodule. It just needed some final adaptations, but apparently also introduced a rather strange `std.math.cmp()` regression on Win32 without optimizations for 64-bit NaNs with custom payload...

**Comment by JohanEngelen** [comment]
nice @kinke

**Comment by kinke** [comment]
Appreciated. Whoever has an MS account (AFAICT, mandatory) is free to join the Azure ldc-developers organization, we'll figure out how. ;) - It's not absolutely crucial, as anyone can create their own Azure project and automatically use the YAML files, just in case I wouldn't be around anymore.

**Pull request merged**
