### PR TITLE
Phobos: Enable x87 asm versions for std.math.{tan,expi}

### PR DESCRIPTION
**Pull request by kinke**
Following #2854.

### CODE REVIEW

**Comment by pineapplemachine** [comment]
I haven't got an inline asm tangent or sincos implementation to work with LDC yet. However, I did have some apparent success with this particular part of the problem by declaring `immutable nan = real.nan` for DMD and `static immutable nan = real.nan` for LDC (each failed to compile for the other) and then writing `fld nan; ret;` inside the `asm` block instead of `return real.nan;` outside of it.

**Comment by kinke** [comment]
> static immutable nan = real.nan

That should have the same problem when compiled as PIC (`-relocation-model=pic`), the global won't be accessible directly.

**Comment by kinke** [comment]
Revived this with a viable workaround for PIC (pass `real.nan` as extra default parameter); the x87 asm version is more than 3x faster than the generic 'software' one on my Ivy Bridge, tested on Linux x64 with `-O` and:
```D
void main()
{
    enum MAXITER = 1 << 20;

    import std.datetime.stopwatch;
    import std.math;
    import std.stdio;

    real sum = 0;

    auto sw = StopWatch(AutoStart.yes);
    for(uint i; i < MAXITER; i++)
        sum += tan(real(i));
    sw.stop();

    writeln(sw.peek.total!"msecs", "ms\t", sum);
}
```

**Comment by kinke** [comment]
The x87 asm for `std.math.expi()` is faster by ~5x (`expi(real(i) / MAXITER)`) to ~12x (`expi(real(i))`) on my box.

**Pull request merged**
