### PR TITLE
object.classinfo: Return a TypeInfo_Class instead of a TypeInfo_Interface

### PR DESCRIPTION
**Pull request by kinke**
This may be enough to fix https://github.com/ldc-developers/ldc/issues/1471 (at least there's no crash anymore for @rainers' minimal testcase).

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Could you also add a testcase for this?

Perhaps something like:
```D
// RUN: %ldc -c -output-ll -of=%t.ll %s && FileCheck %s < %t.ll

class Node
{
    final void _clone()
    {
// CHECK-NOT: load %object.TypeInfo_Interface*
// CHECK: load %object.TypeInfo_Class*
        this.classinfo.create();
    }
}
```

**Comment by kinke** [comment]
Thanks for the ready-to-paste test, but I'm not convinced this deserves a test on its own; it rather seems like a bug due to lack of focus or a typo to me, with an extremely low probability of being reintroduced. ;)
Let's see if it passes the tests and whether it also fixes Rainer's problems first.

**Comment by JohanEngelen** [comment]
OK. Pretty much the first thing I think of now is: "does it have tests?" More tests, more better ;-)
 I am not sure the IR has to be checked, but a simple "does it compile" check would be nice, no? It would check for many other things besides your typo ;)

**Comment by kinke** [comment]
I'm pretty sure this typo isn't mine. ;)
Yeah that's what I meant (not checking the IR, just checking whether it compiles and works), but I'd rather see such tests go upstream so that all compilers benefit (I don't know whether GDC uses dmd-testsuite too, but I guess and hope so) from improved test coverage. DMD's test coverage is pretty bad, especially wrt. basic compiler and language stuff - https://github.com/ldc-developers/ldc/issues/1327 wouldn't exist if there was a good test coverage for the evaluation order of expressions.

**Comment by JohanEngelen** [comment]
Opps, sorry misread :(
Upstreaming is good.

**Comment by rainers** [comment]
LGTM, but I haven't tried it yet (I replaced all occurences with typeid). I wonder why this isn't lowered to TypeidExp in the front end, though. 
A test should verify runtime behaviour, too.

**Comment by kinke** [comment]
This may not be correct. `TypeidExp` returns a `TypeInfo_Interface` for interfaces, not a `TypeInfo_Class`. Don't know if that is supposed to happen for `.classinfo` too.

**Comment by rainers** [comment]
According to the doc and Kenji, `typeid()` and `.classinfo` are supposed to do the same. There have been some discussions around what should be returned and that strange things happen with dmd, too: https://github.com/dlang/dmd/pull/4711, https://issues.dlang.org/show_bug.cgi?id=14612 and a number of linked reports.

**Comment by kinke** [comment]
Updated so that .classinfo for interfaces returns a TypeInfo_Interface, as before and compatible to `TypeidExp` codegen.

**Comment by rainers** [comment]
LGTM. It's compatible with dmd with respect to not returning the actual class for interfaces.

**Pull request merged**
