### PR TITLE
Small jit fixes

### PR DESCRIPTION
**Pull request by Hardcode84**
* Better thunks stripping from jit module.
* Fixes to jit disassembler
* Strip comdats from jit module

### CODE REVIEW

**Comment by JohanEngelen** [comment]
No tests added?

**Comment by Hardcode84** [comment]
@JohanEngelen I will add tests after I figure out how to test it :)

**Comment by Hardcode84** [comment]
added some tests

**Comment by JohanEngelen** [comment]
Looks like the test uncovered an issue on Windows?

**Comment by Hardcode84** [comment]
There is only spurious failure on travis now. I am merging it now.

**Pull request merged**
