### PR TITLE
Specify explicit seed for test, to see if it reproduces on CI server

### PR DESCRIPTION
**Pull request by JohanEngelen**
related to https://github.com/ldc-developers/ldc/pull/4328

The seed comes from this failed CI run: https://github.com/ldc-developers/ldc/actions/runs/4266350680/jobs/7426765564

### CODE REVIEW

**Comment by JohanEngelen** [comment]
I tried on Mac but it does not reproduce with this seed, probably because seeds / inputs / instrumentation is slightly different between platforms and thus won't reproduce the testcase nor the failure.

**Comment by JohanEngelen** [comment]
The seed does not trigger the same error (use after return). Very strange ..

**Comment by kinke** [comment]
The new regex is still in place, so you wouldn't know?

**Comment by JohanEngelen** [comment]
It reproduces on the CI server, but I am not able to reproduce in a docker image x86_64 at home, using Ubuntu 18.04 with ldc-latest-ci (`LDC - the LLVM D compiler (1.31.0-git-d89c00c): based on DMD v2.101.2 and LLVM 15.0.7`). CI uses LLVM LLVM 15.0.6, could that matter?

**Comment by kinke** [comment]
I've seen it fail for the `Main` GH Actions workflow too (which uses our LLVM v15.0.7), e.g., https://github.com/ldc-developers/ldc/actions/runs/4263313148/jobs/7419888009 (seed 3337776564). And I think for the Linux aarch64 Cirrus CI job too.

**Comment by JohanEngelen** [comment]
Ah, I now see that stack-use-after-return is automatically _enabled_ with LLVM15 (we set it to "runtime"), I didn't know that.
https://clang.llvm.org/docs/AddressSanitizer.html#stack-use-after-return-uar

**Comment by JohanEngelen** [comment]
Closing, because I think the fix is OK.

**Pull request closed without merging**
