### PR TITLE
Add ON/OFF to lit.site.cfg.in s.t. cmake flags can be set directly

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
lgtm, but is there anything in particular that moved you to make this change?

**Comment by thewilsonator** [comment]
I was getting a bunch of errors from a stale build directory, I don't know why. I think I meant to submit this PR ages ago but never got around to it, must have been from when I applied it locally.

**Comment by thewilsonator** [comment]
I'm pretty sure `LDC_DYNAMIC_COMPILE` can ben made to use this too, but that can wait for another PR.

**Comment by thewilsonator** [comment]
Semaphore timed out and the travis failure is unrelated.

**Pull request merged**
