### PR TITLE
Refactor toir visit(StringExp) to avoid un-necessary computations.

### PR DESCRIPTION
**Pull request by looked-at-me**
This doesn't include peekData() as described in https://github.com/ldc-developers/ldc/issues/3490 not sure about the process about updating the interface files, if it's fine I'll just add it into this PR.

### CODE REVIEW

**Comment by kinke** [comment]
> not sure about the process about updating the interface files

You could just add an inline wrapper returning a `DString`, analogous to https://github.com/ldc-developers/ldc/blob/1494343d6e2687234339fa6c6a242dd5a7003eff/dmd/expression.h#L386-L393

**Comment by kinke** [comment]
Thx for figuring out the test failures. - Seems like the code duplication is pointless, so this should be further refactored. It doesn't have to be you, and it doesn't have to be in this PR, but it's ugly as hell once one knows about it.

**Comment by kinke** [comment]
Thx! I've pushed 2 more commits and am finally satisfied. ;)

**Comment by looked-at-me** [comment]
LGTM, the failure is due to a timeout. Not sure if you want to run it again?

**Comment by kinke** [comment]
I've learned to accept unfortunate sporadic failures and CI hickups. [Plus I can't retrigger or cancel Travis jobs as I used to.]

In case you're wondering about the formatting - we use clang-format for a consistent C++ style.

**Pull request merged**
