### PR TITLE
druntime: Cherry-pick libunwind-based backtrace alternative and use it for musl targets

### PR DESCRIPTION
**Pull request by kinke**
Testing https://github.com/ldc-developers/druntime/pull/192.

### CODE REVIEW

**Comment by Geod24** [comment]
```
Scanning dependencies of target druntime-ldc-unittest-debug
[ 74%] Building C object runtime/CMakeFiles/druntime-ldc-unittest-debug.dir/druntime/src/core/stdc/errno.c.o
[ 74%] Building C object runtime/CMakeFiles/druntime-ldc-unittest-debug.dir/druntime/src/ldc/arm_unwind.c.o
[ 74%] Building C object runtime/CMakeFiles/druntime-ldc-unittest-debug.dir/druntime/src/ldc/msvc.c.o
[ 74%] Building ASM object runtime/CMakeFiles/druntime-ldc-unittest-debug.dir/druntime/src/core/threadasm.S.o
[ 74%] Building ASM object runtime/CMakeFiles/druntime-ldc-unittest-debug.dir/druntime/src/ldc/eh_asm.S.o
[ 74%] Linking D static library ../lib/libdruntime-ldc-unittest-debug.a
[ 74%] Building C object runtime/CMakeFiles/phobos2-ldc-unittest-shared.dir/phobos/etc/c/zlib/inftrees.c.o
[ 74%] Built target druntime-ldc-unittest-debug
[ 74%] Building C object runtime/CMakeFiles/phobos2-ldc-unittest-shared.dir/phobos/etc/c/zlib/trees.c.o
[ 74%] Building C object runtime/CMakeFiles/phobos2-ldc-unittest-shared.dir/phobos/etc/c/zlib/uncompr.c.o
[ 74%] Building C object runtime/CMakeFiles/phobos2-ldc-unittest-shared.dir/phobos/etc/c/zlib/zutil.c.o
Scanning dependencies of target druntime-test-runner
[ 74%] Linking C executable druntime-test-runner
[ 74%] Linking C shared library ../lib/libphobos2-ldc-unittest-shared.so
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/effortman/projects/bpfk/docker-ldc/ldc/src/ldc/lib/libdruntime-ldc-unittest.a(handler.o): in function `_D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu':
handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0x7b): undefined reference to `unw_getcontext'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0x86): undefined reference to `unw_init_local'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0xa4): undefined reference to `unw_step'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0xf6): undefined reference to `unw_get_proc_name'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0x126): undefined reference to `unw_get_proc_info'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: handler.d:(.text._D4core8internal9backtrace7handler16LibunwindHandler6__ctorMFNbNimZCQCoQCmQCgQBzQBu+0x142): undefined reference to `unw_step'
collect2: error: ld returned 1 exit status
make[3]: *** [runtime/CMakeFiles/druntime-test-runner.dir/build.make:137: runtime/druntime-test-runner] Error 1
make[2]: *** [CMakeFiles/Makefile2:1200: runtime/CMakeFiles/druntime-test-runner.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 80%] Built target phobos2-ldc-unittest-shared
make[1]: *** [CMakeFiles/Makefile2:510: runtime/CMakeFiles/all-test-runners.dir/rule] Error 2
make: *** [Makefile:333: all-test-runners] Error 2
```

Fails to link, and I'm a bit puzzled why. It obviously checks out your branch [link](https://github.com/bpfkorea/docker-ldc/blob/52830b05059b8be65d069ed144491785b932e2e9/ldc/APKBUILD#L32-L40) and the config file is [minimally modified](https://github.com/bpfkorea/docker-ldc/blob/master/ldc/01-conf.patch) although in a relevant way.

**Comment by kinke** [comment]
Thx for checking - `C_SYSTEM_LIBS` ([link](https://github.com/ldc-developers/ldc/blob/bdc317e6488db581fe409535dafab999cd8a9894/runtime/CMakeLists.txt#L125-L136)) will most likely need to be specified manually for the CMake invocation for musl (adding `-DC_SYSTEM_LIBS="unwind m pthread rt dl"`) unless you know of a way to detect musl in CMake.

**Comment by Geod24** [comment]
> adding `-DC_SYSTEM_LIBS="unwind;m;pthread;rt;dl"`

This seems to have done the trick. Compilation has succeeded and I'm now running tests (but since I'm on Mac, it takes a while).

**Comment by Geod24** [comment]
All tests passed.

**Comment by kinke** [comment]
Btw, you could replace the `ldc2.conf` patch by providing `-DADDITIONAL_DEFAULT_LDC_SWITCHES=' "-linker=bfd", "-link-defaultlib-shared"' in the CMake cmdline.

**Comment by Geod24** [comment]
@kinke : Any plan for a second beta / a release date ?

**Comment by Geod24** [comment]
> Btw, you could replace [...]

Good to know, thanks! I'll try to rework it when I update the package.

**Comment by kinke** [comment]
A 2nd beta isn't planned ATM (this being the only change from beta1); final release probably soon after v2.095.**1**.

**Pull request merged**
