### PR TITLE
[Android] druntime: Handle TLS init issues

### PR DESCRIPTION
**Pull request by kinke**
Wrt. #3461 and the encountered issue with the rdmd executable.

### CODE REVIEW

**Comment by MaskRay** [comment]
You only need to overalign the first section in PT_TLS (typically .tdata, but .tss is possible as well).

https://reviews.llvm.org/D62055

**Comment by kinke** [comment]
The code currently makes no assumptions about which section comes first in the final binary.

**Comment by kinke** [comment]
Hmm, doesn't seem to have any effect. The section sizes are identical, so it looks like the dummy symbols are stripped, ignoring the `llvm.used` directives.

**Comment by MaskRay** [comment]
Then the comment is wrong.

   // Enforce some minimum alignment for both .tdata and .tbss sections,
    // to have the first section appropriately padded and hence the second
    // section (expected to be adjacent) ending up suitably aligned in each
    // thread's TLS block.

**Comment by kinke** [comment]
The comment is incomplete anyway (but writing down all details seemed not worth it), and should do if you don't relate `first` and `second` to the order in the opening sentence, but the sections order in the final binary, as traversed by the code.

**Comment by JohanEngelen** [comment]
> Hmm, doesn't seem to have any effect. The section sizes are identical, so it looks like the dummy symbols are stripped, ignoring the `llvm.used` directives.

I recently found out that llvm.used / assumeUsed is only a directive to the "compiler" but not to the "linker". So the linker may still discard the symbol...

**Comment by kinke** [comment]
It works fine for our ModuleInfos...

**Comment by kinke** [comment]
Now apparently working as expected - for AArch64, but not for ARMv7-A (sections not adjacent; alignment would be fine). I've checked the 32-bit ARM ld scripts included in the used Android NDK r21, and all of them specify .tdata right before .tbss, but that doesn't correspond to the final layout.

**Comment by kinke** [comment]
Okay, I've checked all 3 linkers for both AArch64 and ARMv7-A - the only one placing both sections adjacent to each other is bfd, for both archs. So it looks like the NDK uses different default linkers, depending on arch...

**Comment by JohanEngelen** [comment]
> It (assumeUsed) works fine for our ModuleInfo refs...
> 
> **Edit**: And https://github.com/ldc-developers/druntime/blob/f5e154743d844c5ec1ea3b086abb6daca6e1713b/src/rt/sections_elf_shared.d#L971 also appears to assume this just works (not even using @assumeUsed there).

I discovered that things are kept when explicitly accessing the magic start/stop linker symbols. Without that, `lld` discarded many symbols at Weka.

**Comment by kinke** [comment]
@PetarKirov: Please give the aarch64 artifact at https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=1780&view=results a quick check. The executables should all work.

There's one remaining issue though, an apparent disagreement of the NDK and Termux wrt. `-fuse-ld=bfd` - for the NDK, it's required (as default `ld` is gold for all archs but AArch64, where it's bfd); according to your tests, Termux doesn't support it on AArch64, and so requires an explicitly empty `-linker=` (or `-linker=ld`) with this PR. I can add that as default option for future Termux packages, but the official package wouldn't work out of the box in Termux anymore (at least the AArch64 one).

**Comment by kinke** [comment]
> I discovered that things are kept when explicitly accessing the magic start/stop linker symbols. Without that, lld discarded many symbols at Weka.

Yeah, I remember the issues we've had with ModuleInfos refs potentially being stripped by older bfd versions, in combination with `--gc-sections`. And as it happens, the bundled bfd for the latest Android NDK (a few days old) is v2.27, which is from 2016. - It's a pain in the ass trying to outsmart the optimizer.

**Comment by kinke** [comment]
The complications with 2 separate sections being aggregated to a single contiguous memory block could presumably also be handled in our LLVM fork, e.g., by emitting zero-initialized TLS stuff into `.tdata` too. I think that would only increase the executable file size; with a single section, all linkers would work, and users will never be forced to overalign `.tdata` manually.

**Comment by kinke** [comment]
@PetarKirov: Will you be able to quickly check this in the next couple of days? It'd be nice for the final 1.22 release, but I won't delay it by much more.

**Comment by PetarKirov** [comment]
Hi @kinke, sorry for the delay, but as I mentioned previously I'm not able to keep up with GitHub notifications, so it's best to contact me either via the dlang slack or via email.

I've checked both the ldc 1.22.0 package from Termux and the [ldc2-1.22.0-android-aarch64](https://github.com/ldc-developers/ldc/releases/download/v1.22.0/ldc2-1.22.0-android-aarch64.tar.xz) archive from GitHub. The Termux package works out of the box and the official one works after I add `-linker=ld`  to the switches section of ldc2.conf, as otherwise it fails with:
```
clang-9: error: invalid linker name in argument '-fuse-ld=bfd'
Error: /data/data/com.termux/files/usr/bin/cc failed with status: 1
```

This is because BFD is named just `ld`, whereas the other linkers are `ld.gold` and `ld.lld` respectively.

**Comment by kinke** [comment]
Yeah I've known about missing `ld.bfd` for Termux, at least on AArch64. I consider that a Termux issue, as the NDK obviously has the symlink.

**Pull request merged**
