### PR TITLE
[AppVeyor] Update LLVM package

### PR DESCRIPTION
**Pull request by JohanEngelen**
My 1st attempt to create LLVM packages for AppVeyor.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@redstar I cherry-picked your LLVM 3.9 fixes into this branch. Locally, this now builds fine on Windows.

**Comment by JohanEngelen** [comment]
@redstar Thanks for submitting a separate PR for the LLVM3.9 stuff. Removed it from this one.

**Comment by kinke** [comment]
I just did the same and compiled r270356 locally, and I've upgraded to VS2015 Update 2. I can reproduce the corrupt PDB issue for `runnable\opover2.d`, but only when using `-enable-inlining`.

**Comment by JohanEngelen** [comment]
@kinke What do you think? Shall we pull this so that we at least we have the AppVeyor builds compile again?

**Comment by kinke** [comment]
Yep. :)

**Comment by majnemer** [comment]
@kinke To reproduce, do I need to do anything other than send opver2.ll into llc?  Also, what was the last version of LLVM which worked?

**Comment by kinke** [comment]
@majnemer The MS linker complains about a corrupt PDB. I don't know how to generate the PDB with LLVM-standalone tools and neither how to squeeze a bit more infos out of the linker (`/verbose` produces a ton of output, but a quick glance didn't reveal something useful). I'll update the zip and include the object file and PDB.
We've previously been using an LLVM build from a couple of months ago (r263591, which worked), so I sadly can't tell you when it broke. Johan's first attempt with r270175 already exhibited this issue. Sorry for the lack of further infos. :/

**Comment by majnemer** [comment]
The IR you gave me doesn't work with LLVM fa4edb6, can you give me IR which works with that revision so that I can compare the object files produced by fa4edb6 and trunk.  Alternatively, you could attach the good and bad object files.

**Comment by kinke** [comment]
Here's [IR and a good object file](https://dl.dropboxusercontent.com/s/5r8i4nzjzr0m4r2/opover2-good.zip?dl=0) based on exactly the same source, built with our latest successful Win64 CI binaries from a week ago (and LLVM fa4edb6).

**Comment by majnemer** [comment]
If you use LLVM 41f296b5d3af49b9028ce9efe3c0d8ba7cf811fc, do you still get the invalid PDB issues?

**Comment by kinke** [comment]
Well to find out I'll have to build LLVM and LDC + runtimes first, that'll take at least 30 min, so I hope it's worth it. ;)

**Comment by majnemer** [comment]
I think it will be worth it, there are too many differences between the old and new object files to tell what's going on.  There have been a lot of "cleanups" and 41f296b5d3af49b9028ce9efe3c0d8ba7cf811fc is both a fairly recent revision yet the last revision before those cleanups.

**Comment by kinke** [comment]
Very good guess, it payed off, this works:
```
LDC - the LLVM D compiler (8a3d1c):
  based on DMD v2.071.0 and LLVM 3.9.0git-41f296b
  built with DMD32 D Compiler v2.071.0
```
So I've used the same LDC commit from one week ago as our latest CI build. So this one works with LLVM fa4edb6 and 41f296b. I've updated the [good archive](https://dl.dropboxusercontent.com/s/5r8i4nzjzr0m4r2/opover2-good.zip?dl=0).

**Comment by majnemer** [comment]
Ah, things are getting more clear :)

The bad dump has "<unknown UDT>" where the good dump is fine.

Would you mind trying ef598a795b358cdd3ff034c56c816afa1e96b8e9?

**Comment by kinke** [comment]
Perfect. ef598a7 still works too. Just in case, here's the [object file](https://dl.dropboxusercontent.com/s/z0q9wwqmxe1zjoo/opover2-ef598a7.obj?dl=0).

**Comment by majnemer** [comment]
Great, very few changes left to look at.
My gut says that d06ea8a8f4b9994b6d26f09d5079fd18e865e095 should work and be9d2489d18be6fce2863553feeb07295e96a426 should break.  Would you mind giving that a shot?

**Comment by kinke** [comment]
I'll check the 2 over night and get back to you. Thanks man!

**Comment by majnemer** [comment]
No problem!  Sorry that I don't have a better way of triaging this one :/

**Comment by kinke** [comment]
Your gut was correct. :)

**Comment by majnemer** [comment]
Many thanks for your testing.  I was able to reduce the test down to a trivial amount of LLVM IR and reverted LLVM r270106 in r270389.

**Comment by JohanEngelen** [comment]
@kinke @majnemer Great work tracking this down so fast.

**Comment by majnemer** [comment]
LLVM r270106 has been relanded as r270485.  Let me know if you guys hit any more snags.

**Comment by kinke** [comment]
Thanks a lot @majnemer. We'll keep on upgrading from time to time. ;)

**Pull request merged**
