### PR TITLE
ftime-trace: add tracing of CTFE !

### PR DESCRIPTION
**Pull request by JohanEngelen**
`--ftime-trace` was not yet tracing CTFE, a major oversight... With these changes it now _does_ trace CTFE. The start, and function calls during CTFE. I think that gives the user enough info to pinpoint where time is spent.

Testcase gives this output:

image

@rikkimax

### CODE REVIEW

**Comment by JohanEngelen** [comment]
about CI errors: Perhaps `dmd-2.102.2-beta.1` miscompiles ?
(it's annoying to test with DMD on macOS, because I have to rebuild LLVM for x86_64 arch......)

**Comment by JohanEngelen** [comment]
> about CI errors: Perhaps `dmd-2.102.2-beta.1` miscompiles ?

Pff, I'm a bit rusty it seems... `version (LDC) ---> version (IN_LLVM)`. doh!

**Comment by JohanEngelen** [comment]
@kinke I'd like to get this in the release, automerge enabled.

**Comment by JohanEngelen** [comment]
@rikkimax This should be available in `ldc-latest-ci` (install.sh), see here: https://github.com/ldc-developers/ldc/releases/tag/CI

**Comment by rikkimax** [comment]
There appears to be something wrong with that build (even without time-trace), its take >3 minutes to build what should take sub-40 seconds normally. Was it not optimized?

Perfetto can no longer work with the resulting trace, when scrolled out. Ah I think I know why, ``CTFE start: [33, 33, 33, 33, 3`` ... giant Unicode table here. Yeahhhh the name field needs to be shrunk. If the name is bigger than what a symbol name can be please truncate. After all how many kilobytes do you need to know its a table?

I've included a screenshot of a problem module, and yeahhhh that tells a much better story.
Capture

**Comment by JohanEngelen** [comment]
> There appears to be something wrong with that build (even without time-trace), its take >3 minutes to build what should take sub-40 seconds normally. Was it not optimized?
> 
> Perfetto can no longer work with the resulting trace, when scrolled out. Ah I think I know why, `CTFE start: [33, 33, 33, 33, 3` ... giant Unicode table here. Yeahhhh the name field needs to be shrunk. If the name is bigger than what a symbol name can be please truncate. After all how many kilobytes do you need to know its a table?

please submit bug reports whenever you find something ;-).  (this one I can remember)

**Pull request merged**
