### PR TITLE
GHA: Switch to Docker image for Alpine workflow

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
@JohanEngelen: Your call. :)

**Comment by JohanEngelen** [comment]
lol, it's this easy !? I didn't know this is possible.  I don't see any downside to this.

**Comment by JohanEngelen** [comment]
(I guess with this solution, and installing `bash` on Alpine, the other scripts won't need as much adjustment)

**Comment by kinke** [comment]
Yeah exactly, at least we shouldn't need to tweak `shell` anymore with this.

**Pull request merged**
