### PR TITLE
Raise min LLVM version to 6.0

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
I wasn't really sure whether to raise to 5 or 6, but went with 6 in the end, mostly because most non-ancient distro versions ship with v6 or newer, see https://pkgs.org/download/llvm. E.g., Ubuntu jumped directly from v3.8 (16.04) to v6.0 (18.04), and Debian from v3.8 (stretch) to v7.0 (buster), so most users shouldn't be affected.

**Comment by dnadlinger** [comment]
LLVM 6 was released in March 2018, so should be fine in that respect.

The only reason to hold off on this I can see would be if someone has a weird custom backend that is pre-6 only.

**Comment by JohanEngelen** [comment]
The amount of code lines this removes is incredible.

**Comment by kinke** [comment]
Heh yeah, but most of it is just our version-specific profdata/FileCheck copies.

**Comment by kinke** [comment]
I've given the guys a week to respond to the forum thread, I think that's enough.

**Comment by Geod24** [comment]
This broke Buildkite: https://buildkite.com/dlang/dmd/builds/14258#2579093e-dd2a-478a-8ae0-ef6f30275231

**Pull request merged**
