### PR TITLE
Travis: use LLVM3.9 on OS X

### PR DESCRIPTION
**Pull request by JohanEngelen**
Let's see if this works (so that we can release with LLVM3.9 on OS X).

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Homebrew does not have llvm3.9 yet.

See:
https://github.com/Homebrew/homebrew-core/pull/4579
https://github.com/Homebrew/homebrew-versions/pull/1384

**Comment by JohanEngelen** [comment]
Instead of waiting for homebrew, I rewrote travis.yml to download the binaries from LLVM directly and cache them like we do for the Linux builds.  This appears to speed up the build a lot (~39min -> ~30min), possibly because LLVM's binaries have all assertions disabled?

**Comment by JohanEngelen** [comment]
(green for mac with LLVM3.9 btw, nice :-))

**Comment by kinke** [comment]
> possibly because LLVM's binaries have all assertions disabled

Seems like it, as we don't have assertions enabled on Linux as well. I must say I really prefer CI builds with enabled assertions; people keep complaining about LDC crashing, and most of these issues (and others!) would be caught by enabled assertions. I would even prefer alphas and betas to ship with assertions too.
Does CircleCI have assertions enabled or is it just AppVeyor now?

**Comment by JohanEngelen** [comment]
Pretty sure that CircleCI also does not have assertions enabled...

Hm.

**Comment by JohanEngelen** [comment]
Already merged in release-1.1.0 branch.

**Pull request merged**
