### PR TITLE
Implement 128bit atomic load, atomic store and cmpxchg.

### PR DESCRIPTION
**Pull request by redstar**
This is required for compiling latest vibe.d version.
Please note that a fix to vibe.d is also required, see
https://github.com/rejectedsoftware/vibe.d/pull/1255

### CODE REVIEW

**Comment by kinke** [comment]
This breaks the Win64 build, due to an undefined reference to `ldc.intrinsics.llvm_atomic_load()` in unittest line `core.atomic:1539`. I've also tried `core.atomic.atomicStore()` and `cas()` with the 128-bit struct, and both functions crash at runtime.

**Comment by redstar** [comment]
I check this. I encountered the undefined reference only with older LLVM versions which do not support the i128 atomic intrinsics. A crash may also be due to a misalign. 128bit structs must be `align(16)`. dmd seems to do this for dynamic arrays but I don't understand why.

**Comment by redstar** [comment]
The undefined reference is mysterious. But I do not have crashes with `atomicStore()` and `cas()`. Commenting out the load and the next line makes all tests pass.

**Comment by kinke** [comment]
Gets even more mysterious. I use a test file like this:

```D
import core.atomic;
import core.stdc.stdio;

struct DoubleValue
{
    long value1;
    long value2;
}

void main()
{
    align(16) shared DoubleValue a = DoubleValue(1,2);
    atomicStore(a, DoubleValue(1,2));
    printf("a.value1: %lld, a.value2: %lld\n", a.value1, a.value2);
//    assert(a.value1 == 1 && a.value2 ==2);

//    while(!cas(&a, DoubleValue(1,2), DoubleValue(3,4))){}
//    printf("a.value1: %lld, a.value2: %lld\n", a.value1, a.value2);
//    assert(a.value1 == 3 && a.value2 ==4);

//    align(16) DoubleValue b = atomicLoad(a);
//    assert(b.value1 == 3 && b.value2 ==4);
}
```

I can confirm that `atomicStore()` _appears_ to work (output is okay). What doesn't work is the following assert, although it should be satisfied - I once got a crash in our EH personality function (when calling `nativeContext.getLanguageSpecificData()` in ldc.eh.common:406, but most of the time it's a segfault (write) in `RtlDispatchException()`, if our debug infos are to be trusted. ;)
If I comment out the atomicStore, then the first assert doesn't crash... %)

`cas()` always crashes in `RtlDispatchException()`.

**Comment by kinke** [comment]
Bugger:

```LL
define i32 @_Dmain({ i64, { i64, i8* }* } %unnamed) #0 {
  %a = alloca %hello.DoubleValue, align 8         ; [#uses = 2, size/byte = 16]
  %.structliteral = alloca %hello.DoubleValue     ; [#uses = 3, size/byte = 16]
  %.ExplicitByvalRewrite_putResult = alloca %hello.DoubleValue, align 16 ; [#uses = 2, size/byte = 16]
  %1 = bitcast %hello.DoubleValue* %a to i8*      ; [#uses = 1]
  call void @llvm.memset.p0i8.i64(i8* %1, i8 0, i64 16, i32 1, i1 false)
  %2 = getelementptr %hello.DoubleValue, %hello.DoubleValue* %.structliteral, i32 0, i32 0 ; [#uses = 1, type = i64*]
  store i64 1, i64* %2
  %3 = getelementptr %hello.DoubleValue, %hello.DoubleValue* %.structliteral, i32 0, i32 1 ; [#uses = 1, type = i64*]
  store i64 2, i64* %3
  %4 = bitcast %hello.DoubleValue* %.ExplicitByvalRewrite_putResult to i8* ; [#uses = 1]
  %5 = bitcast %hello.DoubleValue* %.structliteral to i8* ; [#uses = 1]
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %4, i8* %5, i64 16, i32 1, i1 false)
  call void @_D4core6atomic88__T11atomicStoreVE4core6atomic11MemoryOrderi3TS5hello11DoubleValueTS5hello11DoubleValueZ11atomicStoreFNaNbNiKOS5hello11DoubleValueS5hello11DoubleValueZv(%hello.DoubleValue* noalias nocapture %.ExplicitByvalRewrite_putResult, %hello.DoubleValue* %a)
  ret i32 0
}
```

1. ABI rewrite for call to intrinsic (new value rewritten by `ExplicitByvalRewrite`). I guess you expect it to be passed directly as struct type.
2. `a` is aligned on a 8-bytes boundary, `align(16)` apparently ignored. The `ExplicitByvalRewrite` is properly aligned, but only because that's a Win64 ABI requirement.

**Comment by kinke** [comment]
Oh I think I found the reason for the undefined reference to llvm_atomic_load - the TargetABI rewrites the function type (sret) of the intrinsic!

```
* * * * * * * * * * DtoSymbolAddress ('llvm_atomic_load' of type 'pure nothrow @nogc @safe UCent(shared(const(UCent*)) ptr, AtomicOrdering ordering = cast(AtomicOrdering)7)')
* * * * * * * * * * * FuncDeclaration
* * * * * * * * * * * DtoFunctionType(pure nothrow @nogc @safe UCent(shared(const(UCent*)) ptr, AtomicOrdering ordering = cast(AtomicOrdering)7))
* * * * * * * * * * * * Building type: UCent*
* * * * * * * * * * * * Building type: shared(const(UCent))*
* * * * * * * * * * * * Building type: AtomicOrdering
* * * * * * * * * * * * Final function type: void (%"core.atomic._AtomicType!(DoubleValue).UCent"*, i32, %"core.atomic._AtomicType!(DoubleValue).UCent"*)
* * * * * * * * * * * DtoResolveFunction(ldc.intrinsics.llvm_atomic_load!(UCent).llvm_atomic_load): C:/LDC/ninja-ldc/import\ldc\intrinsics.di(424)
* * * * * * * * * * * * DtoDeclareFunction(ldc.intrinsics.llvm_atomic_load!(UCent).llvm_atomic_load): C:/LDC/ninja-ldc/import\ldc\intrinsics.di(424)
* * * * * * * * * * * * * DtoFunctionType(pure nothrow @nogc @safe UCent(shared(const(UCent*)) ptr, AtomicOrdering ordering = cast(AtomicOrdering)7))
* * * * * * * * * * * * * func =
declare void @_D3ldc10intrinsics82__T16llvm_atomic_loadTS4core6atomic38__T11_AtomicTypeTS5hello11DoubleValueZ5UCentZ16llvm_atomic_loadFNaNbNiNfOxPS4core6atomic38__T11_AtomicTypeTS5hello11DoubleValueZ5UCentE3ldc10intrinsics14AtomicOrderingZS4core6atomic38__T11_AtomicTypeTS5hello11DoubleValueZ5UCent(%"core.atomic._AtomicType!(DoubleValue).UCent"*, i32, %"core.atomic._AtomicType!(DoubleValue).UCent"*)

* * * * * * * * * DtoCallFunction()
* * * * * * * * * * Building type: pure nothrow @nogc @safe UCent(shared(const(UCent*)) ptr, AtomicOrdering ordering = cast(AtomicOrdering)7)
* * * * * * * * * * * DtoFunctionType(pure nothrow @nogc @safe UCent(shared(const(UCent*)) ptr, AtomicOrdering ordering = cast(AtomicOrdering)7))
* * * * * * * * * * * * Building type: AtomicOrdering
* * * * * * * * * * * * Final function type: void (%"core.atomic._AtomicType!(DoubleValue).UCent"*, i32, %"core.atomic._AtomicType!(DoubleValue).UCent"*)
```

**Comment by redstar** [comment]
Good catch!

**Pull request merged**
