### PR TITLE
README: Add latest release badge (incl. prereleases) and update notes about prebuilt packages

### PR DESCRIPTION
**Pull request by kinke**
Incl. emphasizing that the package managers are community-maintained, I'm tired of reading the same questions again and again.

### CODE REVIEW

**Comment by Geod24** [comment]
Do you also want to include a link to `setup-dlang` for CIs ?

**Comment by kinke** [comment]
Hmm - it'd be a single CI service only, but my main point would be that the target audience is different - this readme is primarily for first-time users, not guys already familiar with D and setting up CI for their D repos.

**Comment by JohanEngelen** [comment]
> Incl. emphasizing that the package managers are community-maintained, I'm tired of reading the same questions again and again.

to avoid variable interpretation of "community-maintained", perhaps "are not maintained by the LDC project but by the larger D language community" would work even better?

**Comment by kinke** [comment]
I think it's a sufficiently self-describing and established term, some Google results:
* https://github.com/ziglibs/repository: `This is one community-maintained repository of zig packages.`
* https://github.com/openwrt/packages: `This is the OpenWrt "packages"-feed containing community-maintained build scripts...`
* https://community.chocolatey.org/packages: `There are 8513 Community Maintained Packages`

**Comment by kinke** [comment]
@Geod24: I've noticed Alpine is missing - is `apk add ldc` sufficient?

**Comment by Geod24** [comment]
Yes. `edge` is usually updated pretty quickly, stable releases get whatever's current when the release is made.

**Comment by kinke** [comment]
Thx; wrt. dub, yeah that seems to be pretty standard for distro packages (and makes sense).

**Pull request merged**
