### PR TITLE
Apply dmd PR #5842

### PR DESCRIPTION
**Pull request by UplinkCoder**
Cacheing isDataseg gives an overall speed improvement of 10%

I thought it should go into ldc asap.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
https://github.com/dlang/dmd/pull/5842

https://github.com/dlang/dmd/commit/26c2213204c7a52165c7c798ee7d6f3212b26549

**Comment by JohanEngelen** [comment]
Why did Travis not trigger?

**Comment by JohanEngelen** [comment]
Thanks Stefan.

**Comment by UplinkCoder** [comment]
you are welcome.

**Comment by JohanEngelen** [comment]
Good question.
I thought this PR was close enough to an "NFC" to be OK for early inclusion.

I don't know what Kai is planning for the 1.1.0 branch (cherry-picking, or perhaps taking master while still in alpha), but once 1.1.0 is branched I hope we can push towards semi-sync with dmd.

**Pull request merged**
