### PR TITLE
CircleCI: Use LLVM 5.0.0 final

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
The previous issues all seem to be fixed with 5.0.0 final, at last.
There's still the severe `std.datetime` unittests runtime regression, [Circle](https://circleci.com/gh/ldc-developers/ldc/3178):
```
958/1558 Test #285: std.datetime .................................................................   Passed   95.26 sec
1208/1558 Test #672: std.datetime-debug ...........................................................   Passed  111.71 sec
1557/1558 Test #1059: std.datetime-shared ..........................................................   Passed  102.83 sec
1558/1558 Test #1446: std.datetime-debug-shared ....................................................   Passed   87.26 sec
```
vs. [Semaphore](https://semaphoreci.com/ldc-developers/ldc/branches/pull-request-2318/builds/4) with LLVM 4.0.1:
```
368/3114 Test #293: std.datetime ....................................................................   Passed    3.74 sec
754/3114 Test #680: std.datetime-debug ..............................................................   Passed    4.97 sec
1140/3114 Test #1067: std.datetime-shared .............................................................   Passed    3.50 sec
1527/3114 Test #1454: std.datetime-debug-shared .......................................................   Passed    5.59 sec
```

**Comment by kinke** [comment]
I can't test it quickly locally, I has to downgrade to v4.0.1 while working on the debuginfo stuff... ;)

**Comment by kinke** [comment]
@JohanEngelen: A sporadic `ldc_prune_cache` failure again: https://travis-ci.org/ldc-developers/ldc/jobs/273693029#L2133

**Comment by kinke** [comment]
> is that reproducible locally?

Not on my Win64 box; debug takes 9.5 secs, release 2.6.

**Comment by JohanEngelen** [comment]
Don't we want CircleCI to test LLVM trunk?
(thanks for making LLD optional btw)

**Comment by kinke** [comment]
The LLVM APT repo seems way too unreliable for my liking.

**Comment by thewilsonator** [comment]
We have an LLVM fork, could we use circle to build and release LLVM periodically and then use circle for LDC with LLVM master?

**Pull request merged**
