### PR TITLE
fix #2615 installed ldc.conf should set rpath

### LINKED ISSUE #2615: regression: OSX: Library not loaded: @rpath/libdruntime-ldc-shared.78.dylib
/cc @klickverbot 

this used to work with lldb 1.6.0:

https://github.com/timotheecour/dtools/blob/master/dtools/lldbdplugin.d (demangle D in lldb)

ldmd2 -of=liblldbdplugin.dylib -shared -g -I$dtools_D $dtools_D/dtools/modified/demangle.d $dtools_D/dtools/lldbdplugin.d

$path_to/lldb -- $some_program

after upgrading ldc2 (via homebrew) to 1.8.0 it fails; after debugging this is because:
dlopen(/Users/timothee/git_clone/timotheecour/tims/tests/d31_gdb_demangle/liblldbdplugin.dylib, 9): Library not loaded: @rpath/libdruntime-ldc-shared.78.dylib
  Referenced from: /Users/timothee/homebrew/opt/ldc/lib/libphobos2-ldc-shared.78.dylib
  Reason: image not found

## root cause
```
otool -L liblldbdplugin.dylib
liblldbdplugin.dylib:
        liblldbdplugin.dylib (compatibility version 0.0.0, current version 0.0.0)
        /Users/timothee/homebrew/opt/ldc/lib/libphobos2-ldc-shared.78.dylib (compatibility version 78.0.0, current version 2.0.78)
        /Users/timothee/homebrew/opt/ldc/lib/libdruntime-ldc-shared.78.dylib (compatibility version 78.0.0, current version 2.0.78)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

otool -L /Users/timothee/homebrew/opt/ldc/lib/libphobos2-ldc-shared.78.dylib
/Users/timothee/homebrew/opt/ldc/lib/libphobos2-ldc-shared.78.dylib:
        /Users/timothee/homebrew/opt/ldc/lib/libphobos2-ldc-shared.78.dylib (compatibility version 78.0.0, current version 2.0.78)
        @rpath/libdruntime-ldc-shared.78.dylib (compatibility version 78.0.0, current version 2.0.78)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

#=>  see @rpath/
```

whereas with ldc 1.6.0:
```
otool -L liblldbdplugin.dylib
liblldbdplugin.dylib:
        liblldbdplugin.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

### PR DESCRIPTION
**Pull request by timotheecour**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
I think this shouldn't be in ldc.conf, but instead should be added to the link command line depending on whether shared stdlib is linked with.  Also, the path shouldn't be hardcoded but should use `%%ldcbinarypath%%` instead.

**Comment by kinke** [comment]
> I think this shouldn't be in ldc.conf, but instead should be added to the link command line depending on whether shared stdlib is linked with.

I remember seeing (and disliking) our rpaths in binaries linked with static druntime/Phobos (via non-installed compiler/config file), so only specifying it when linking against shared libs surely makes sense.
If that is supposed to happen for Linux and other Unixoids too, not just OSX, we'd need to forward the MULTILIB_SUFFIX CMake variable to LDC as C++ define (LIB_SUFFIX already is) in order to select the right lib dir for the target bitness. That hardcoded-ness should be fine though.

> Also, the path shouldn't be hardcoded but should use %%ldcbinarypath%% instead.

[The installed config file contains no `%%ldcbinarypath%%` at all. The install path is replaced by that placeholder in a separate step when creating the (portable) release/CI packages, so the patch is consistent with how we handle the install config file. I don't have a problem with using the placeholder from the start in the installed config file though, but I guess distro package maintainers would mind that breaking change.]

**Comment by JohanEngelen** [comment]
Adding rpath selectively is done for sanitizers too: https://github.com/ldc-developers/ldc/blob/856a5730f5978df5990150d835ce11ace192eccc/driver/linker-gcc.cpp#L264-L274

> we'd need to forward the MULTILIB_SUFFIX CMake variable to LDC as C++ define (LIB_SUFFIX already is) in order to select the right lib dir for the target bitness

Does that mean that adjustments are needed here?: 
https://github.com/ldc-developers/ldc/blob/856a5730f5978df5990150d835ce11ace192eccc/driver/exe_path.cpp#L51

**Comment by kinke** [comment]
> Does that mean that adjustments are needed here?

Yep. I still think the main problem is cross-linking though, especially since AFAICT the -rpath ld option doesn't override a previous one (`All -rpath arguments are concatenated and passed to the runtime linker, which uses them to locate shared objects at runtime.` ([src](ftp://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html))), so the user wouldn't be able to override the (partly) hardcoded value injected by LDC.

I'm not even sure LDC should set the rpath automatically, I guess there's a reason it's not added to the installed config file. And I'm also not sure if it should be required for produced shared libs or whether that's another separate issue.

**Comment by timotheecour** [comment]
@kinke @JohanEngelen shall I close this PR? looks like you have a different way in mind for how to fix this. The status quo is not good though, as it introduces a regression when one uses `-shared` (previously worked, now breaks)

**Comment by kinke** [comment]
Superseded by #2659.

**Pull request closed without merging**
