### PR TITLE
aa static storage

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.9 gdb ninja-build
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package g++-4.9
E: Couldn't find any package by glob 'g++-4.9'
E: Couldn't find any package by regex 'g++-4.9'
```

Dunno why that failed.

**Comment by thewilsonator** [comment]
appveyor time out.

**Comment by kinke** [comment]
Diff to c6132508b1e11a76d24cbb744b452775a686fdae, current master~1, before your other PR:
```diff

     if (fd->tok != TOKfunction) {
       assert(fd->tok == TOKdelegate || fd->tok == TOKreserved);
-      e->error("non-constant nested delegate literal expression `%s`",
-               e->toChars());
-      if (!global.gag) {
-        fatal();
+
+      // Only if the function doesn't access its nested context, we can emit a
+      // constant delegate with context pointer being null.
+      // FIXME: Find a proper way to check whether the context is used.
+      //        For now, just enable it for literals declared at module scope.
+      if (!fd->toParent2()->isModule()) {
+        e->error("non-constant nested delegate literal expression `%s`",
+                 e->toChars());
+        if (!global.gag) {
+          fatal();
+        }
+        result = llvm::UndefValue::get(DtoType(e->type));
+        return;
       }
-      result = llvm::UndefValue::get(DtoType(e->type));
-    } else {
-      // We need to actually codegen the function here, as literals are not
-      // added
-      // to the module member list.
-      Declaration_codegen(fd, p);
-      assert(DtoCallee(fd));
+    }

-      result = DtoCallee(fd);
+    // We need to actually codegen the function here, as literals are not
+    // added to the module member list.
+    Declaration_codegen(fd, p);
+
+    result = DtoCallee(fd);
+    assert(result);
+
+    if (fd->tok != TOKfunction) {
+      auto contextPtr = getNullPtr(getVoidPtrType());
+      result = LLConstantStruct::getAnon(gIR->context(), {contextPtr, result});
     }
   }
```

**Comment by kinke** [comment]
I moved it to #2574 with proper revert & rework as Johan requested on gitter.

**Pull request closed without merging**
