### PR TITLE
Fix pip bootstrap URL

### PR DESCRIPTION
**Pull request by thewilsonator**
This error was hit on https://github.com/ldc-developers/ldc/pull/3683

### CODE REVIEW

**Comment by thewilsonator** [comment]
Azure linux/ android gives
```
g++-multilib : Depends: gcc-multilib (>= 4:5.3.1-1ubuntu1) but it is not going to be installed
                Depends: g++-5-multilib (>= 5.3.1-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
noticed on `dlang/dmd` too, unrelated to this.

**Comment by Geod24** [comment]
https://github.com/ldc-developers/ldc/pull/3680

**Comment by kinke** [comment]
Thx; I wanted to keep on experimenting with #3680 for Travis AArch64 but lost all interest in the meantime. Merged now, so at least this annoyance is resolved; for Azure Linux, where MS manages to f*ck this up regularly, we'll probably have to wait for a fix on their end.

**Comment by thewilsonator** [comment]
Thanks!

**Pull request closed without merging**
