### PR TITLE
druntime: Add {load,store}Unaligned and prefetch to core.simd

### PR DESCRIPTION
**Pull request by kinke**
This tests a revised https://github.com/ldc-developers/druntime/pull/163.

### CODE REVIEW

**Comment by kinke** [comment]
Pinging @baziotis.

**Comment by baziotis** [comment]
It took me 2 minutes to find the changes. :P
Indeed, it makes sense to keep for LDC all the unittests since those will be relevant for the DMD "overload". But we don't need to add tests for any other vectors, since those are supposed to be handled by what was already there (the LDC overload).

**Comment by kinke** [comment]
Yes, and the 128-bit vectors should suffice, as it's the same thing over and over.

I had to add an explicit function wrapping the IR implementation, just aliasing wouldn't work. The `ElementType` alias wouldn't work either.

**Comment by baziotis** [comment]
> I had to add an explicit function wrapping the IR implementation, just aliasing wouldn't work. The `ElementType` alias wouldn't work either.

My bad. I'm still struggling to see why.

**Comment by kinke** [comment]
I think it's something along these lines:

* Compiler sees `float4* p; loadUnaligned(p);`.
* It has seen eponymous template `loadUnaligned(V)` with an inner `loadUnaligned` alias and a `loadUnaligned(const V*)` function. In order to expand the alias and check whether it'd be a better fit (e.g., mutable `loadUnaligned(V*)`), the template would have to be instantiated already, as the IR function type depends on `ElementType`, `llvmT` enum etc. - but the compiler is still checking which of the 2 overloads for which `V` template parameter fits best, in order to infer `V` and only then instantiating the template.

**Comment by baziotis** [comment]
> I think it's something along these lines:
> 
> * Compiler sees `float4* p; loadUnaligned(p);`.
> * It has seen eponymous template `loadUnaligned(V)` with an inner `loadUnaligned` alias and a `loadUnaligned(const V*)` function. In order to expand the alias and check whether it'd be a better fit (e.g., mutable `loadUnaligned(float4*)`), the template would have to be instantiated already, as the IR function type depends on `ElementType`, `llvmT` enum etc. - but the compiler is still checking which of the 2 overloads for which `V` template parameter fits best, in order to infer `V` and only then instantiating the template.

Subtle. Thanks!

**Pull request merged**
