### PR TITLE
Add preliminary support for LLVM 19

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by liushuyu** [comment]
I also have a LLVM 19 port based on the work in this pull request: https://github.com/liushuyu/ldc/tree/llvm-19

**Comment by kinke** [comment]
With more success? My mild enthusiasm was immediately killed by that LLVM assertion, which after a quick glance seemed to be an LLVM regression (as we're just trying to get some intrinsic by name).

**Comment by liushuyu** [comment]
> With more success? My mild enthusiasm was immediately killed by that LLVM assertion, which after a quick glance seemed to be an LLVM regression (as we're just trying to get some intrinsic by name).

Yes, so mine worked around the LLVM assertions by providing the overloaded types to the intrinsic functions.

**Comment by liushuyu** [comment]
> Oh great! Any reason for not opening an MR? I mean I'm fine with cherry-picking too if you don't want to yourself.

I opened the pull request at https://github.com/ldc-developers/ldc/pull/4772. Some CI setups are required to get LLVM 19 binaries.

**Pull request closed without merging**
