### PR TITLE
CI: Add vanilla LLVM 15 job on Linux

### PR DESCRIPTION
**Pull request by kinke**
Just testing a rebased #4257 + an LLVM 15 job on Linux, as v15.0.6 has an x86_64 Ubuntu package again...

### CODE REVIEW

**Comment by kinke** [comment]
The defaultlib tests with LLVM 15 are hanging on Linux too...

**Comment by JohanEngelen** [comment]
> The defaultlib tests with LLVM 15 are hanging on Linux too...

:(   I think it's https://github.com/ldc-developers/ldc/issues/4261 ?

**Comment by JohanEngelen** [comment]
I forgot, do we default to `--opaque-pointers=false` with LLVM15? (higher chance of working)

**Comment by thewilsonator** [comment]
Unless we changed it to true, no.

**Comment by JohanEngelen** [comment]
> I forgot, do we default to `--opaque-pointers=false` with LLVM15? (higher chance of working)

Just tested, we default to `--opaque-pointers=true`.
We can force opaque pointers like this hack (needs better location but this works):
```diff
diff --git a/driver/main.cpp b/driver/main.cpp
index b36971195b..72890c14c5 100644
--- a/driver/main.cpp
+++ b/driver/main.cpp
@@ -998,6 +998,7 @@ void registerPredefinedVersions() {
   }

 #if LDC_LLVM_VER >= 1400
+  getGlobalContext().setOpaquePointers(false);
   // A version identifier for whether opaque pointers are enabled or not. (needed e.g. for intrinsic mangling)
   if (!getGlobalContext().supportsTypedPointers()) {
     VersionCondition::addPredefinedGlobalIdent("LDC_LLVM_OpaquePointers");
```
It breaks some tests because we wrote the IR matching for opaque ptr work (e.g. missing bitcasts), but on my machine I also run into some LLVM assertions (possibly bugs in our code with pointer comparisons or smth).

LLVM15 fully supports typed pointers, so it's OK to force typed pointers if it makes LDC work. LLVM16 only supports typed pointers on "best-effort" basis, untested.

**Comment by kinke** [comment]
Right, hitting stuff like this now after rebase + hack:
```
Stored value type does not match pointer operand type!
  store %nest.__unittest_L291_C9* %8, i8** %18, align 8, !dbg !516
```

**Comment by kinke** [comment]
Okay, I seem to have found & fixed the culprit, see last commit. - With typed pointers now, the LLVM 15 job on Mac is green, while there's a single `druntime-test-exceptions-release` failure on Linux.

**Comment by kinke** [comment]
Oh and I override LLVM's `-opaque-pointers` option now - in order to default to `false` for now, independent from LLVM version. When we have proper support for opaque pointers, we can get rid of it again and use LLVM's default setting.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
