### PR TITLE
Drop support for LLVM < 3.7

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by thewilsonator** [comment]
LGTM.

**Comment by JohanEngelen** [comment]
Nice. Merge when you are happy with it @kinke 

IIRC, ArrayRef now accepts initializer lists, right?

**Comment by thewilsonator** [comment]
ArrayRef has accepted initialiser lists for quite a while I think.

**Comment by kinke** [comment]
Yep, good catch, it's guaranteed to be there for LLVM 3.7+; for 3.5 and 3.6 `LLVM_HAS_INITIALIZER_LISTS` had to be defined. So there may be room for some simplifications (as well as re-clang-formatting; I only reformatted a few places manually to keep the diff clearer).

**Pull request merged**
