### PR TITLE
Disambiguate that -link-defaultlib-shared can take a parameter

### PR DESCRIPTION
**Pull request by p0nce**
So that nobody asks the #3168 question again.

### CODE REVIEW

**Comment by kinke** [comment]
All boolean flags can take a parameter (LLVM default); IIRC, Seb Wilzbach didn't know that either, so maybe we should add a general text somewhere (and just mention for this flag that it defaults to `true` with `-shared` and that this can be explicitly disabled).

**Comment by p0nce** [comment]
The problem being that you won't stumble on the general text so it should be discoverable at the use point no?

**Comment by dnadlinger** [comment]
If it's at the bottom of the `--help` output, hopefully users would stumble over it.

**Comment by p0nce** [comment]
Updated.

**Comment by kinke** [comment]
Slightly revised, incl. getting rid 80 columns limit (no limit for the other help output either).

**Pull request merged**
