### PR TITLE
Dcompute semantic

### PR DESCRIPTION
**Pull request by thewilsonator**
This will need to be rebased for ldc-developers/druntime#87 once ldc-developers/ldc:dcompute tracks ldc-developers/druntime:dcompute.

See the comments in https://github.com/ldc-developers/ldc/pull/1953 for the reasons for the horrible hack in the if statement visitor.

I am inexperienced in lit so I hope that this is the right format for and that the errors match.
(the tests are expected to fail until tracking druntime:dcompute)

### CODE REVIEW

**Comment by JohanEngelen** [comment]
> This will need to be rebased for ldc-developers/druntime#87 once ldc-developers/ldc:dcompute tracks ldc-developers/druntime:dcompute.

(If this is already familiar to you, I'm very sorry. I'm a little confused about this comment :S)

If you mean by "tracking" that the ldc:dcompute branch automatically uses the (latest) druntime:dcompute branch, then unfortunately, that is not possible. The ldc:dcompute branch has to explicitly specify which druntime commit hash it is using (as submodule). So in practice, what happens is that first you commit to a druntime repo (ldc-developers/druntime:dcompute), and then you have to make a commit to ldc:dcompute to make it point to the new druntime commit hash. See e.g. this LDC commit that also changed the druntime submodule hash: https://github.com/ldc-developers/ldc/commit/b5d1ae2ca114d17e04abd407e17b59cb67158ad0

For this PR, you have to set your local druntime submodule to druntime:dcompute and make that part of this PR by adding it to a commit (on cmdline, `git add runtime/druntime`).


I'm very happy to see this PR btw! :)

**Comment by JohanEngelen** [comment]
wait a minute, i see that in one commit you reverted a druntime hash change. But that's exactly what you need to do! :) So I guess you do already know about how it works, sorry for the needless explanation. I'm confused now :(

**Comment by thewilsonator** [comment]
> or this PR, you have to set your local druntime submodule to druntime:dcompute and make that part of this PR by adding it to a commit (on cmdline, git add runtime/druntime).

Ah thats how you do that! I was wondering how you were able to get submodule commits appearing. Lets see if this works.

**Comment by thewilsonator** [comment]
Urgh, i'm getting submodule merge conflicts.

 >  I'm confused now :(

What I want is this PR *as is* ( subject to any requested changes ofc) except with the druntime submodule at 202eb9607de175ccbef7307e3cb6aeaefd55ebd0 (after the merge of https://github.com/ldc-developers/druntime/pull/87). You are able to edit this PR, please do.

I hope that makes sense, I'm way over my head in git for this and completely lost.

**Comment by JohanEngelen** [comment]
You should rebase this branch onto ldc:dcompute.
The reason you get merge conflicts is that you are changing it from 02cc057 to something else, but ldc:dcompute is at 6d4cf2. To fix it, you should rebase this branch onto ldc:dcompute, and _then_ change druntime hash. (note that your last commit changes it to 81eb instead of 202eb)

**Comment by thewilsonator** [comment]
Oohh, thanks. I'll do it tomorrow when I'm more awake.

**Comment by thewilsonator** [comment]
Got really stuck, blasted everything started afresh, #1993.

**Pull request closed without merging**
