### PR TITLE
Add predefined version CRuntime_Musl

### PR DESCRIPTION
**Pull request by kinke**
Wrt. issue #2341.

### CODE REVIEW

**Comment by kinke** [comment]
The question is whether `CRuntime_Glibc` should be defined too, to minimize the required druntime patches, as it seems to basically work out of the box already.

**Comment by joakim-noah** [comment]
Ideally we'd just define `CRuntime_Musl` and patch druntime to only need that, as I've done with Bionic before, but obviously this pull will get them up and running much quicker, as you say.  [I've opened a forum thread on microservices](http://forum.dlang.org/thread/twtbrappuarwhyzlchrb@forum.dlang.org), hopefully we can get some feedback and help on this issue.

**Comment by kinke** [comment]
I added an unrelated patch due to the refactoring taken place in the first commit. It replaces the fatal error for an unknown target OS (with the MSP430 exception) with a warning, to allow for bare-metal targets.

**Comment by kinke** [comment]
There's a first `CRuntime_Musl` occurrence in 2.078 (`core.sys.posix.poll`), so this should be good to go now.

**Pull request merged**
