### PR TITLE
jit runtime small refactorings

### PR DESCRIPTION
**Pull request by Hardcode84**
* Proper constness
* Moved `createResolver` to separate function
* `enumModules` helper function
* clang-format

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@klickverbot Could you give @Hardcode84 commit rights so he can commit accepted PRs ?

**Comment by JohanEngelen** [comment]
@Hardcode84 Did you use the "rebase and merge" button perhaps? The PR number is missing from the commit message.  If you use "squash and merge", Github adds the PR number in parens, so we can trace back the story of how and why something was added. If you don't want to squash commits, then a normal merge also notes the PR number in the merge commit.

**Comment by Hardcode84** [comment]
@JohanEngelen Yeah, sorry about that. This wasn't clear from github description.

**Comment by JohanEngelen** [comment]
no prob, that's why i disabled it now :-)

**Pull request merged**
