### PR TITLE
Enforce static default libs with cmdline option -static

### PR DESCRIPTION
**Pull request by kinke**
Wrt. issue #2646.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
No testcase?

**Comment by kinke** [comment]
It's not [trivially] testable for BUILD_SHARED_LIBS=ON configs, as used for Travis.

**Comment by JohanEngelen** [comment]
Can't we do a `not %ldc -v -static -link-defaultlib-shared  %s | FileCheck %s` and check the `-v` output?  (with requires: Linux)
(add a reference to a missing symbol in the D source such that the linking will always error)

**Comment by kinke** [comment]
Oh I didn't think about enforcing a linking failure. - Test amended.

**Pull request merged**
