### PR TITLE
New LLVM for dcompute

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@thewilsonator Could you update to LLVM 6 instead? That should be stable and then we have stable (note: *stable*) testing going on. The LLVM 6 bug that the tester found was pretty bad. Right now this is the only tester we have for LLVM 6...

**Comment by thewilsonator** [comment]
Hmm, I can try. My git-fu is not very good, migrating the commits is going to be difficult. I'm also in London for work until the 17th.

Is there any reason we can't add or upgrade one of the linux boxes?

**Comment by JohanEngelen** [comment]
@thewilsonator Can i bug you again about this? Would be good to have stable testing of dcompute (i.e. LLVM 6)

**Comment by thewilsonator** [comment]
Sorry I've been rather busy, I'll see if I can do it Sunday.

**Comment by thewilsonator** [comment]
@JohanEngelen Done.

**Comment by JohanEngelen** [comment]
rebased onto master

**Comment by JohanEngelen** [comment]
I can reproduce the `codegen/dcompute_cl_addrspaces.d` failure locally, but dyncompile tests run fine on my machine.

**Comment by JohanEngelen** [comment]
merging, because it improves things (failures were already present)

**Comment by JohanEngelen** [comment]
dyncompile failures are because of the testserver building with `cmake -DBUILD_SHARED_LIBS=OFF`. Possibly related to this: https://github.com/ldc-developers/ldc/issues/2615

**Pull request merged**
