### PR TITLE
fix build against LLVM trunk svn rev 273030

### PR DESCRIPTION
**Pull request by rainers**
new argumets to GlobalValue::setUnnamedAddr

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@rainers Can you try updating the links in appveyor.yml to these?

```
If ($Env:APPVEYOR_JOB_ARCH -eq 'x64') {
    Start-FileDownload 'https://dl.dropboxusercontent.com/s/kqsr5haxoiz9nly/LLVM-r273081-x64.7z?dl=0' -FileName 'llvm-x64.7z'
} Else {
    Start-FileDownload 'https://dl.dropboxusercontent.com/s/tp9acj30ww0yekh/LLVM-r273081-x86.7z?dl=0' -FileName 'llvm-x86.7z'
}
```

btw, FileCheck-3.9.cpp also needs a change on line 1309: `sys::PrintStackTraceOnErrorSignal(argv[0]);`
Or you can just copy LLVM trunk's FileCheck.cpp on top of it.

**Comment by kinke** [comment]
`utils\FileCheck-3.9.cpp:1302` needs to be updated too. It should probably be a copy of the current LLVM file.

**Comment by rainers** [comment]
Updated both.

**Comment by JohanEngelen** [comment]
Fingers crossed!

**Comment by kinke** [comment]
It's looking good, thx guys!

**Comment by JohanEngelen** [comment]
Very good news: finally I can try and merge PGO!

**Pull request merged**
