### PR TITLE
[WIP] Eliminate branch when the condition is false

### PR DESCRIPTION
**Pull request by baziotis**
Partially solving (i.e. only false conditions): https://github.com/ldc-developers/ldc/issues/2344
It does _not_ work! You can even see that 2 test cases I added fail. Now that I saw the issue again, I should add a test case for labels.
I'm uploading just for opinions. Essentially the problems are:
* Doesn't test for loops. Probably every statement (if, for, while - probably there are others I can't think now) should be handled separately.
* The `false_cond_with_else.d` should be easy to pass. Fortunately, the front-end breaks an `else if (cond)` to `else { if (cond) }` so if there is an else body, that should be handled.
* The label thing is the one I'm not sure about. Check all the statements in the body for a label statement ? I don't know.. I'll come back to it.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Some comments:
- focus on `if(0)` in this PR, do all the other things later
- I would omit the constant propagation testing in the tests here
- for labels, indeed I think the only thing you can do is search all statements for labels... This is painful. Perhaps you can first work on adding that functionality to the semantic analysis in the frontend. It would probably be cheap to store a list all labels in a function during semantic analysis because you are already iterating over all statements. Discuss it with the frontend people, I think it may make sense for other functionality aswell to have this information more readily available.

**Comment by JohanEngelen** [comment]
Also: try and find out how DMD, GDC, (and Clang)  tackle this problem.

**Comment by baziotis** [comment]
> Some comments:
> 
> * focus on `if(0)` in this PR, do all the other things later
> * I would omit the constant propagation testing in the tests here
> * for labels, indeed I think the only thing you can do is search all statements for labels... This is painful. Perhaps you can first work on adding that functionality to the semantic analysis in the frontend. It would probably be cheap to store a list all labels in a function during semantic analysis because you are already iterating over all statements. Discuss it with the frontend people, I think it may make sense for other functionality aswell to have this information more readily available.

Great thanks! I think it's better to close this PR and open a new more specific one. I'll ask on slack if we have any info for labels and how difficult would be for me to add it.

**Comment by baziotis** [comment]
> Also: try and find out how DMD, GDC, (and Clang) tackle this problem.

I believe this is a very good advice. Unfortunately, and these are only things I've heard not that I have worked with any of the two: the DMD back-end is one of the most obscure (i.e. pretty much only Walter understands it). The GDC front-end too (i.e. only Iain understands it). I'll have a look at them, but I dare to say that maybe the most approachable is Clang.

**Comment by baziotis** [comment]
Continues here: https://github.com/ldc-developers/ldc/pull/3134

**Pull request closed without merging**
