### PR TITLE
Re-enable LLVM 3.8 and upgrade OS X build to LLVM 3.7.

### PR DESCRIPTION
**Pull request by redstar**

### CODE REVIEW

**Comment by redstar** [comment]
Too early.

**Comment by JohanEngelen** [comment]
Progress can be tracked here:
https://github.com/travis-ci/apt-source-whitelist/pull/255
https://github.com/travis-ci/apt-package-whitelist/issues/2764
https://github.com/travis-ci/apt-package-whitelist/issues/2765

**Comment by JohanEngelen** [comment]
@redstar LLVM 3.8 should be back up on Travis.

**Comment by redstar** [comment]
Thanks. I try it now.

**Pull request closed without merging**
