### PR TITLE
Finalize support for LLVM 10

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
The tested LDC-LLVM here is based on v10 RC1+ (2-3 days old) and includes MLIR. The Android builds have been upgraded to NDK r21.

**Comment by kinke** [comment]
Looking good, just a small LTO regression on Windows wrt. `@weak`. - Switching LLVM back to v9.0.1.

**Comment by kalev** [comment]
Nice, thanks for doing the llvm 10 support -- I appreciate this as a distro package maintainer.

**Comment by kinke** [comment]
You're welcome - I hope there are no last-second API changes...

**Pull request merged**
