### PR TITLE
druntime: Add RISC-V support in core/thread/osthread.d

### PR DESCRIPTION
**Pull request by kinke**
From https://github.com/ldc-developers/druntime/pull/204.

### CODE REVIEW

**Comment by kinke** [comment]
@JohanEngelen @thewilsonator: Let's freeze druntime and dmd-testsuite after this. I'll push a tag `ldc-pre-monorepo` to both repos (from the latest `ldc` branch respectively) and then prepare the monorepo locally on my box. Then we can archive both repos.

**Comment by JohanEngelen** [comment]
> @JohanEngelen @thewilsonator: Let's freeze druntime and dmd-testsuite after this. I'll push a tag `ldc-pre-monorepo` to both repos (from the latest `ldc` branch respectively) and then prepare the monorepo locally on my box. Then we can archive both repos.

This is OK for me!

**Comment by JohanEngelen** [comment]
Please also push the `ldc-pre-monorepo` tag to LDC.

**Comment by JohanEngelen** [comment]
> Please also push the `ldc-pre-monorepo` tag to LDC.

Ah wait, I guess this we need to do only when it is really the pre-monorepo commit. So ignore this for now.

**Comment by JohanEngelen** [comment]
Github: "We recommend that you close all issues and pull requests, as well as update the README file and description, before you archive a repository."

When archiving a repo, you can still see all PRs, they just become readonly. So that's OK, no need to close.
Let's edit the "About" text to indicate that the repo is archived because the contents have become part of the LDC repository (preferably with commit SHA and LDC version).

**Comment by kinke** [comment]
Yeah we can iron out the archiving details (I was also just thinking about editing the 'About' text instead of pushing an extra commit for README.md) after the tag, hence some freeze-period between final tag and actual archiving.

The actual merge in the LDC repo will be something like:
1. tag latest master as `pre-monorepo`
2. commit 1: remove druntime and dmd-testsuite submodules
3. commit 2: merge with the DMD rewrite, tag `dmd-rewrite-first-merged-dmd-druntime-with-ldc-druntime-patches`, keeping our files in `dmd/`. druntime already has all our mods.
4. commit 3: apply the LDC-specific dmd-testsuite diff.

I think this should be it; maybe another little commit is required for some adaptations.

I've already checked for extra/missing files in `dmd/`, `runtime/druntime/` and `tests/dmd`, looks all good. I've also made sure the druntime files don't differ (just a few files with trailing newline changes).

And dmd master from a few hours ago doesn't have any new DMD source files added after tag `first-merged-dmd-druntime`.

**Pull request merged**
