### PR TITLE
Fix #4266: unreachable with dcompute and intrinsics

### LINKED ISSUE #4266: Unreachable "expected FuncDeclaration overload to be used" in `NVPTXTargetABI::callingConv(LINK)`
https://github.com/libmir/dcompute/issues/72

broken in https://github.com/ldc-developers/ldc/commit/dc25da95577960d567a7e84c6056453c66973fa3 as part of [#3917](https://github.com/ldc-developers/ldc/pull/3917)

That overload _is called for_ intrinsics (that are implicitly forced to have the C ABI).

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
@kinke what's the release schedule of LDC looking like? This is a pretty major bug that renders dcompute non-operable with 1.29 and 1.30.

**Comment by thewilsonator** [comment]
cc @aferust can you please confirm this fixes the issue

**Comment by kinke** [comment]
> what's the release schedule of LDC looking like?

I can't promise anything, but I find hardly any time for LDC these days. First I need to fix the last issue/regression in #4141, then do the monorepo, then sync with v2.101.0 and see what needs to be implemented, and ideally, we'd invoke the C preprocessor for importC too. And if there's some time left, do the LLVM 15 fork and use that for the release.

**Comment by thewilsonator** [comment]
hmm, yes, sounds like you are busy. If that will take some time, perhaps a point release would get this fix out a lot faster? 
I'd be happy to do one but I've go no idea what the process is.

**Comment by kinke** [comment]
Well, nobody has officially complained about this particular bug in 7 months since v1.29.0, so I doubt lots of people care. - The process basically boils down to creating a new release branch from the latest release tag, cherry-picking the fix, then
* preparing the GitHub release (changelog) as draft,
* pushing a new tag and immediately publishing the GitHub release (some CI systems require the release to be published to get the artifacts up there), and verifying all relevant CI systems succeed without sporadic failures (otherwise retrying)
* then forum post + https://github.com/ldc-developers/ldc-developers.github.io/blob/master/LATEST bump.

**Comment by thewilsonator** [comment]
> Well, nobody has officially complained about this particular bug in 7 months since v1.29.0, so I doubt lots of people care.

Indeed, but it is a complete showstopper for those that do. Lack of a working release is only an issue if you think 1.31 will take O(months) rather than O(weeks). Someone will need to the changelog anyway, I'll start with that and aim to be done by the weekend (still recovering from covid, over the nasty bits).

Thanks for the quick response.

**Comment by aferust** [comment]
> cc @aferust can you please confirm this fixes the issue

I am building the LDC with your modifications at the moment. I will confirm hopefully

**Comment by aferust** [comment]
> cc @aferust can you please confirm this fixes the issue

@thewilsonator 

Yes, it worked (both build and test for compute).

**Comment by thewilsonator** [comment]
Thanks, I'll work on getting this into a release.

**Pull request merged**
