### PR TITLE
Do not generate DI for non-integral enum types.

### PR DESCRIPTION
**Pull request by LemonBoy**
Found while working on DMD's DWARF output, I have no idea if the test works but you get the point :)

### CODE REVIEW

**Comment by kinke** [comment]
Is that (integral enums only) a general DWARF limitation?

**Comment by LemonBoy** [comment]
Not quite as the DWARF specification doesn't impose any constraint on the `DW_AT_const` but it seems gdb doesn't like non-integral enums.

**Comment by kinke** [comment]
Visual Studio doesn't like float enums either (`<Unable to read memory>`).

**Comment by JohanEngelen** [comment]
Instead of testing that the debuginfo is not an enum, perhaps you can test that the debugger shows something sane?

**Comment by ljmf00** [comment]
> Not quite as the DWARF specification doesn't impose any constraint on the `DW_AT_const` but it seems gdb doesn't like non-integral enums.

They do. `DW_AT_const_value` is required to be a numeric value.

> Each enumerator entry has a DW_AT_name attribute, whose value is a null-terminated string containing the name of the enumeration literal. Each enumerator entry also has a DW_AT_const_value attribute, whose value is the actual numeric value of the enumerator as represented on the target system.

**Comment by ljmf00** [comment]
Any updates on this @LemonBoy ?

**Comment by kinke** [comment]
@ljmf00: Only integral enums are represented as DI enums these days, non-integral ones as typedefs, see https://github.com/ldc-developers/ldc/blob/3701684d6f3a615c911310a1fb5069493b6240d5/gen/dibuilder.cpp#L343-L348

**Comment by ljmf00** [comment]
> @ljmf00: Only integral enums are represented as DI enums these days, non-integral ones as typedefs, see
> 
> https://github.com/ldc-developers/ldc/blob/3701684d6f3a615c911310a1fb5069493b6240d5/gen/dibuilder.cpp#L343-L348

Thanks. I just searched for DWARF related PRs to see what was in progress and didn't notice this was superseded.

**Pull request closed without merging**
