### PR TITLE
CMake: Add option COMPILE_D_MODULES_SEPARATELY & get Shippable CI green again

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by joakim-noah** [comment]
Btw, given the constant timeouts on Travis and Appveyor, would it be worth trying out [Drone instead](https://drone.io)? I think [they might have a free option for OSS projects](https://mobile.twitter.com/bradrydzewski/status/1062843437169266689).

**Comment by kinke** [comment]
The AppVeyor timeouts are everything but constant; I know the jobs tend to lately, but they've been green for weeks before that. Their machines vary wildly apparently; sometimes a job is done in 45 mins, then it's > 1h.

I couldn't quickly find *any* hardware specs for Drone, so my interest dropped to 0 instantly.

**Comment by joakim-noah** [comment]
The interesting thing about Drone is [their CI software is open source](https://thenewstack.io/drone-io-a-containerized-ci-cd-system-for-cloud-native-development/), so we could modify it or conceivably run it on our own hardware, if we wanted to someday. I think their own hosted service just runs on [all the popular cloud platforms, like AWS, etc. (see bottom of checklist)](https://drone.io/enterprise/)

**Comment by kinke** [comment]
> run it on our own hardware

E.g., on Kai's machines? That would surely be interesting for ARM and PowerPC.

**Pull request merged**
