### PR TITLE
Fix LLVM 6.0 build.

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@thewilsonator thanks :)

**Comment by thewilsonator** [comment]
Whoops forgot to renew the cache. Should work now.

**Comment by JohanEngelen** [comment]
@thewilsonator You didn't build a new enough LLVM trunk.

**Comment by ZombineDev** [comment]
@thewilsonator How about including the commit hash (the commit onto which you rebased your fork) in the file name? That way it should be clear which LLVM version is supported.

**Comment by thewilsonator** [comment]
Hmm, thats odd. I pulled and built it last night. It's even with https://github.com/llvm-mirror/llvm/commits/master which is 2 days old. When I try to build locally without this PR the only error I get is 
```
ldc/driver/archiver.cpp:205:7: error: value of type 'const llvm::Error' is not contextually convertible to
      'bool'
  if (Result) {
      ^~~~~~
/Users/nicholaswilson/d/ldc/driver/archiver.cpp:206:59: error: no member named 'message' in 'llvm::Error'
    fail("error writing '" + ArchiveName + "': " + Result.message());
                                                   ~~~~~~ ^
```
Which suggests that it indeed not recent enough.
IDK whats going on, maybe LLVM's GitHub mirror has stopped working?

**Comment by JohanEngelen** [comment]
It's definitely up-to-date now: https://github.com/llvm-mirror/llvm/blob/master/include/llvm/Support/ToolOutputFile.h#L26

**Comment by thewilsonator** [comment]
Done. IDK, why it was lagging for 2 days, but oh well.

**Comment by thewilsonator** [comment]
Looks like something else has broken in the meantime
```
driver/cl_options_sanitizers.cpp:202:30: error: no matching member function for call to 'inSection'
         sanitizerBlacklist->inSection("fun", mangleExact(funcDecl));
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Users/travis/build/ldc-developers/ldc/llvm-spirv-6.0.0-4/include/llvm/Support/SpecialCaseList.h:89:8: note: candidate function not viable: requires at least 3 arguments, but 2 were provided
  bool inSection(StringRef Section, StringRef Prefix, StringRef Query,
       ^
/Users/travis/build/ldc-developers/ldc/llvm-spirv-6.0.0-4/include/llvm/Support/SpecialCaseList.h:141:8: note: candidate function not viable: requires 4 arguments, but 2 were provided
  bool inSection(const SectionEntries &Entries, StringRef Prefix,
       ^
1 error generated.
```

Doesn't look particularly difficult to fix, though fixing it will break circle. Might Fix it tonight if someone doesn't beat me to it.

**Comment by kinke** [comment]
> though fixing it will break circle

CircleCI uses 5.0 final.

**Pull request merged**
