### PR TITLE
Prefer C runtime over host D compiler for CTFE real_t math

### PR DESCRIPTION
**Pull request by kinke**
In order to simplify bootstrapping LDC on new platforms where ltsmaster's Phobos doesn't support the native `real` type yet, such as AArch64.

### CODE REVIEW

**Comment by kinke** [comment]
I'm not 100% comfortable with this. E.g., LDC uses the C runtime for `std.math.sqrt()` (indirectly via LLVM intrinsics on x86 at least), but does an additional check for `x < 0 => NaN`. The exact semantics need to be checked before merging this.

**Comment by kinke** [comment]
I checked; sqrt() was the only exception, all other CTFE builtins using host runtime's `{core,std}.math` were previously using LLVM intrinsics (with master's druntime/Phobos at least) which boil down to C runtime calls, so there should be no change in behavior after the amended sqrt() fix.

**Comment by thewilsonator** [comment]
Is there any reason this hasn't been pulled yet? 
All CI failures have since been fixed. 
I'll close & reopen to retrigger CI make sure it works and then pull.

**Comment by kinke** [comment]
> Is there any reason this hasn't been pulled yet?

As soon as David's AArch64 support makes it into `ltsmaster`, this PR is obsolete, at least until a new FP type pops up (not very likely, especially since we don't use the PowerPC doubledouble type as D `real`).

**Comment by kinke** [comment]
This is now obsolete, as current master's `dmd.root.ctfloat` makes almost exclusive use of the host compiler's C runtime via `core.stdc.math`. `std.math` is only used for `rint()` and `nearbyint()`, both of which are LLVM intrinsics (for both master and ltsmaster).

**Pull request closed without merging**
