### PR TITLE
Change mangling of extern(C++) ctor.

### PR DESCRIPTION
**Pull request by redstar**
This is a part of issue #1312.

### CODE REVIEW

**Comment by redstar** [comment]
@kinke Does this help for ctor mangling?

**Comment by kinke** [comment]
Thx Kai, I'll check it over the weekend.
So this should allow using C++ ctors from D by just declaring them in D. But this doesn't fix the actual mangling bug in #1312.

**Comment by yebblies** [comment]
Without also matching the ABI, matching mangling is a little dangerous.

**Comment by kinke** [comment]
That's what I thought too. You mean the different destruction rules, right? Does the front-end support argument destruction by the caller for `extern(C++)` functions?

**Comment by yebblies** [comment]
I'm not sure.  The issue I've had trouble with is that D will blit `init[]` over before calling the constructor, while C++ won't.  We should (hopefully) be matching argument destruction correctly for normal C++ calls, or is it different for ctors?

**Comment by kinke** [comment]
> D will blit init[] over before calling the constructor, while C++ won't.

I'd think that a C++ ctor cannot make any assumptions about the initial payload, so I'd consider blitting to be useless (and affecting runtime a bit) but not troublesome.

> We should (hopefully) be matching argument destruction correctly for normal C++ calls

That's what I wanted to hear - very good.

**Comment by yebblies** [comment]
> I'd think that a C++ ctor cannot make any assumptions about the initial payload, so I'd consider blitting to be useless (and affecting runtime a bit when calling it from D) but not troublesome.

When calling a ctor written in C++ from D, yes.  But when going the other way the ctor may not init all fields.

**Comment by kinke** [comment]
> But when going the other way the ctor may not init all fields.

True. That could be compensated for when generating an `extern(C++)` ctor implemented in D by having the front-end inject the blitting at the beginning of the ctor (and omitting the pre-init when calling it from D). We could also simply define the semantics for `extern(C++)` ctors implemented in D as fully C++ compatible, i.e., no implicit pre-init.

**Comment by redstar** [comment]
Closing in favor of https://github.com/dlang/dmd/pull/5884.

**Pull request closed without merging**
