### PR TITLE
Add automatic libFuzzer linking + fuzz test

### PR DESCRIPTION
**Pull request by JohanEngelen**
This depends on first pulling
- [x] #2219

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Right now, only CircleCI has libFuzzer available. 
On my Mac, things work splendid as well :-)

**Comment by JohanEngelen** [comment]
Added potential Android support (untested).

**Comment by JohanEngelen** [comment]
@kinke Any way I can see what the build script is on Semaphore? (also the CMake output would be nice to see in the test report)

**Comment by kinke** [comment]
The build script is what you see - the commands when clicking on a job. If you want access to it, sign up and let me know your account ID so I can add you to the project (apparently no GitHub integration). Beware of the `16 more setup commands` at the top of each job, these are the shared prepended commands and include the CMake output.

**Comment by JohanEngelen** [comment]
>  Beware of the 16 more setup commands at the top of each job,

This.

**Comment by JohanEngelen** [comment]
My ID = https://semaphoreci.com/johanengelen

**Comment by JohanEngelen** [comment]
probably just `-DLDC_INSTALL_LLVM_RUNTIME_LIBS=ON` is needed.

**Comment by JohanEngelen** [comment]
Should we have a way to disable linking with the C++ lib, so that the user has a chance to provide it himself if LDC is assuming the wrong one?

**Comment by JohanEngelen** [comment]
@klickverbot What do you think about the C++ lib thing? How fragile is that?

**Comment by JohanEngelen** [comment]
`-x c++` is recognized but doesn't work (on mac).
I'll add a hidden switch so people can turn off the adding of `-lc++`.

**Pull request merged**
