### PR TITLE
Debuginfo: add inheritance information to classes

### PR DESCRIPTION
**Pull request by rainers**
uses inheritance information for base classes instead of listing base class members in derived classes

### CODE REVIEW

**Comment by kinke** [comment]
I did a quick check on Linux with gdb.

Master:
```
(gdb) info locals
dc = 0x7ffff7ed7000
(gdb) print dc
$1 = (DerivedClass *) 0x7ffff7ed7000
(gdb) print *dc
$2 = {baseMember = 0, derivedMember = 0}
(gdb) print dc.baseMember
$3 = 3
(gdb) print dc.derivedMember
$4 = 7
```

This PR:
```
(gdb) info locals
dc = 0x7ffff7ed7000
(gdb) print dc
$1 = (DerivedClass *) 0x7ffff7ed7000
(gdb) print *dc
$2 = {<BaseClass> = {<Object> = {<No data fields>}, baseMember = 0}, derivedMember = 0}
(gdb) print dc.baseMember
$3 = 3
(gdb) print dc.derivedMember
$4 = 7
```

So the correct member values don't show up when displaying the whole class, but inheritance seems to be working nicely.

**Comment by JohanEngelen** [comment]
@rainers Could you name the CodeView files with "_cv" or "_codeview" at the end (instead of at the start)? That's nicer if we add similar files for other debuggers.

**Comment by rainers** [comment]
> So the correct member values don't show up when displaying the whole class, but inheritance seems to be working nicely.

Ouch, incorrect class members! But that's no change from the master print-out.

**Comment by rainers** [comment]
> @rainers Could you name the CodeView files with "_cv" or "_codeview" at the end (instead of at the start)? That's nicer if we add similar files for other debuggers.

Can do. What whould be the others? _dwarf? We probably need to distinguish gdb and lldb, so _cdb would be appropriate for the codeview files. Maybe we can later also test other windows debuggers (e.g. mago), so using the debugger in the name instead of the debug info format should be best.

**Comment by JohanEngelen** [comment]
I also think adding the debugger name as prefix is better.
Tbh, I don't feel too much for duplication a lot of tests for each debugger. I'd rather check the LLVM IR (note the LLVM comment below: "it's worth remembering that debuggers are not the only consumers of debug info").  But for the cases where the IR output has to be different for different debuggers, it's nice to add these specific tests. 

Related: I think we should add "Debugger Tuning" flags (http://clang.llvm.org/docs/UsersManual.html#controlling-debugger-tuning); I may submit a PR for this. It would replace the `if(target->Windows()){}` for debuginfo, with `if(getDebuggerTuning() != CDB)`, and set the default debugger tuning depending on the target platform. LLVM reads:
```cpp
  /// Identify a debugger for "tuning" the debug info.
  ///
  /// The "debugger tuning" concept allows us to present a more intuitive
  /// interface that unpacks into different sets of defaults for the various
  /// individual feature-flag settings, that suit the preferences of the
  /// various debuggers.  However, it's worth remembering that debuggers are
  /// not the only consumers of debug info, and some variations in DWARF might
  /// better be treated as target/platform issues. Fundamentally,
  /// o if the feature is useful (or not) to a particular debugger, regardless
  ///   of the target, that's a tuning decision;
  /// o if the feature is useful (or not) on a particular platform, regardless
  ///   of the debugger, that's a target decision.
  /// It's not impossible to see both factors in some specific case.
  ///
  /// The "tuning" should be used to set defaults for individual feature flags
  /// in DwarfDebug; if a given feature has a more specific command-line option,
  /// that option should take precedence over the tuning.
  enum class DebuggerKind {
    Default,  // No specific tuning requested.
    GDB,      // Tune debug info for gdb.
    LLDB,     // Tune debug info for lldb.
    SCE       // Tune debug info for SCE targets (e.g. PS4).
  };
```

So perhaps we should try to add "CDB" in there asap :)

**Comment by JohanEngelen** [comment]
(btw, before I forget: when merging this PR, please first squash the commits such that each commit still builds (annoying when individual commits break compilation during bisecting))

**Comment by rainers** [comment]
> So perhaps we should try to add "CDB" in there asap :)

I don't think cdb is a common target because nobody uses it (it could be remoted by some IDE though, I remember DLangIDE used it in the past), windbg would be the more common debugger that probably has similar capabilities. The overwhelming more common debugger is likely to be Visual Studio.

I don't oppose adding debugger tuning flags, but so far we don't have special tuning per debugger on Windows, it's all just about the CodeView debug format. For nice D support I'd expect to support mago features that you would disable with -gc.

**Comment by rainers** [comment]
> (btw, before I forget: when merging this PR, please first squash the commits such that each commit still builds (annoying when individual commits break compilation during bisecting))

Done.

**Comment by JohanEngelen** [comment]
> I don't oppose adding debugger tuning flags, but so far we don't have special tuning per debugger on Windows, it's all just about the CodeView debug format.

I meant this in `dibuilder.cpp`:
```d
    if (global.params.targetTriple->isWindowsMSVCEnvironment()) {
      // VS debugger does not support DW_ATE_UTF for char
```
It'd be very nice to replace the `targetTriple->isWindowsMSVCEnvironment()` with a function that checks for the VS debugger (under the hood it could be doing the same). From my testing it appears that LLDB also does not support DW_ATE_UTF.

**Pull request merged**
