### PR TITLE
Support generic ldc.attributes.llvmAttr UDAs for function parameters

### PR DESCRIPTION
**Pull request by kinke**
E.g., finally enabling `restrict` C(++) semantics.

### CODE REVIEW

**Comment by kinke** [comment]
@JohanEngelen, @dnadlinger et al.: Okay with `@restrict` for C resemblance? Or [additionally] `@noalias`?

**Comment by JohanEngelen** [comment]
I have no preference. Perhaps, if it is named the same as C `restrict`, people will automatically find the C documentation of it.
Can you also add a test for passing a class object?

(pretty nice to have this UDA functionality btw)

**Comment by kinke** [comment]
[Object test added.]

**Comment by JohanEngelen** [comment]
lgtm btw

**Pull request merged**
