### PR TITLE
Add CI job for macOS with LLVM 15

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by JohanEngelen** [comment]
A worrying test failure with LLVM15:
```
893:  ... runnable/test20.d              -g -link-defaultlib-debug ()==============================
893: Test 'runnable/test20.d' failed. The logged output:
893: /Users/runner/work/ldc/ldc/bin/ldmd2 -conf= -m64 -Irunnable -g -link-defaultlib-debug  -od../../../dmd-testsuite-debug/runnable -of../../../dmd-testsuite-debug/runnable/test20_0  runnable/test20.d 
893: ../../../dmd-testsuite-debug/runnable/test20_0  --DRT-testmode=run-main
893: core.exception.AssertError@core/internal/util/array.d(58): Array lengths don't match for copy: 9 != 2
893: ----------------
893: ??:? onAssertErrorMsg [0x10f194e1e]
893: ??:? _d_assert_msg [0x10f195375]
893: ??:? nothrow @safe void core.internal.util.array._enforceSameLength(const(char[]), const(ulong), const(ulong)) [0x10f1bde38]
893: ??:? nothrow @safe void core.internal.util.array.enforceRawArraysConformable(const(char[]), const(ulong), const(void[]), const(void[]), const(bool)) [0x10f1bdc83]
893: ??:? _d_array_slice_copy [0x10f1d365d]
893: ??:? void test20.test51() [0x10ef3ff6f]
893: ??:? _Dmain [0x10ef4168a]
```

**Comment by JohanEngelen** [comment]
I found the problem, it is related to opaque pointers:
`arrays.cpp` contains code like this:
```d
  LLValue *realLhsPtr = DtoArrayPtr(lhs);
  if (realRhsArrayPtr && realRhsArrayPtr->getType() == realLhsPtr->getType())
```
With opaque pointers, we *cannot* do this kind of type comparison, because it will always be true. I'll work on a fix for this case, but I worry about undetected other bugs in our code with opaque pointers due to this...

**Comment by JohanEngelen** [comment]
I think we need to review all uses of `->getType() ==`.
Potential bugs with opaque pointers (the list is longer):

```d
gen/irstate.cpp:
  137                                   LLConstant *initializer,
  138                                   Dsymbol *symbolForLinkageAndVisibility) {
  139:   if (initializer->getType() == globalVar->getValueType()) {
  140      defineGlobal(globalVar, initializer, symbolForLinkageAndVisibility);
```
```d
gen/llvmhelpers.cpp:
  462        }
  463  #else
  464:       assert(r->getType() == lit);
  465  #endif
  466      }
  ...
  514  
  515    LLValue *rval = DtoRVal(val);
  516:   if (rval->getType() == tolltype) {
  517      return new DImValue(_to, rval);
  518    }
  ...
  615      if (fromsz == tosz) {
  616        rval = DtoRVal(val);
  617:       assert(rval->getType() == tolltype);
  618      } else if (fromsz < tosz) {
  619        rval = new llvm::FPExtInst(DtoRVal(val), tolltype, "", gIR->scopebb());
  ...
  798      LLType *tll = DtoType(tb);
  799  
  800:     if (rval->getType() == tll) {
  801        return new DImValue(to, rval);
  802      }
```

Assert bugs:
```d
gen/dvalue.cpp:
   77  
   78  DConstValue::DConstValue(Type *t, LLConstant *con) : DRValue(t, con) {
   79:   assert(con->getType() == DtoType(t));
   80  }
   ...
  158  
  159  DSpecialRefValue::DSpecialRefValue(Type *t, LLValue *v) : DLValue(v, t) {
  160:   assert(v->getType() == DtoPtrToType(t)->getPointerTo());
  161  }
```

```d
gen/functions.cpp:
  896          // The argument is an appropriate lvalue passed by reference.
  897          // Use the passed pointer as parameter storage.
  898:         assert(irparam->value->getType() == DtoPtrToType(paramType));
```

**Comment by JohanEngelen** [comment]
I don't like adding more LLVM15 fixes to this PR.
@kinke  @thewilsonator  Are you OK with merging this PR, i.e. enabling LLVM15 macOS testing, while that CI job fails? Can we mark it as a known failure?

**Comment by thewilsonator** [comment]
Thats fine with me. Thanks for finishing this up!

**Comment by JohanEngelen** [comment]
Looks like there is an infinite loop somewhere in the LLVM15 build (possibly related to opaque pointers XD)

**Comment by JohanEngelen** [comment]
I've separated the code fixes into this PR: https://github.com/ldc-developers/ldc/pull/4263

I guess it's not good to have a never ending CI job... so will take a bit longer before this PR can be merged.

**Comment by kinke** [comment]
Superseded by / incorporated in #4307.

**Pull request closed without merging**
