### PR TITLE
[Travis] Do the LLVM binaries work on Ubuntu 12?

### PR DESCRIPTION
**Pull request by JohanEngelen**
(seem to for Boost.Hana)

### CODE REVIEW

**Comment by kinke** [comment]
Oh yeah baby, looking good. It also fixes the sharedlib issue. WTF?!

**Comment by kinke** [comment]
Damn, multilib still times out. ~1h 20 min?! Are the LLVM binaries slower than the packages we've used previously?

**Comment by JohanEngelen** [comment]
> or the host machines we get this way are just slower.

With this PR we should be back on the same systems as before instead of switching to the Ubuntu 14 machines.

**Comment by JohanEngelen** [comment]
merge?

**Comment by kinke** [comment]
Yes, the longer time-out alone is worth it.

**Pull request merged**
