### PR TITLE
Add range metadata when loading bools

### PR DESCRIPTION
**Pull request by kinke**
When optimizing the code, analogous to clang, fixing one aspect of issue #2131.

### CODE REVIEW

**Comment by kinke** [comment]
Johan's seemingly simpler testcase `void foo(bool x, ref bool o) { o |= x; }` still doesn't work, i.e., `x` is still ANDed with 1 in optimized assembly; I guess we do need `zeroext` for bool params after all.

**Comment by JohanEngelen** [comment]
For the testcase, I like `void foo(bool x, ref bool o) { o |= x; }` much better because it doesn't depend on any imported module or cross-module inlining.
(in my tests, zeroext didn't matter)

**Comment by kinke** [comment]
`zeroext` is necessary. There's no explicit `and` anymore in the optimized IR already after the first commit, but there is in assembly unless `zeroext` is used in the 2nd commit. Switched to the simpler test case as that's working properly now too.

**Comment by kinke** [comment]
> This can wait if you don't feel particularly inspired

Yep, not feeling too inspired about refactoring this tiny check for an active `-O` switch into something bigger. Maybe something for another time though (incl. caching of that metadata node?).

Good to go into 1.3?

**Comment by JohanEngelen** [comment]
lgtm

**Pull request merged**
