### PR TITLE
driver/gen/ir: clang-format the world

### PR DESCRIPTION
**Pull request by klickverbot**
This uses the LLVM style, which makes sense for sharing code
with other LLVM projects. The DMD code we use will soon all
be in D anyway.

### CODE REVIEW

**Comment by redstar** [comment]
I'm ok with reformatting the source. I found the inconsistent style in the source always confusing.

**Comment by kinke** [comment]
Puh... ;)
The first impression is (surprisingly) pretty good, although I'm really no friend of `T *` and `T &`, and very much prefer `T*` instead. Other than that, I guess 'll have to get used to a mini-indentation of 2 spaces, and the compact curly braces syntax (opening `{` on same line).

**Comment by redstar** [comment]
@kinke It's not so tought. I did some LLVM development and this style is pretty ok.

**Comment by redstar** [comment]
Is there an example for an Git hook using clang-format available? (Windows,Linux,OS X?) This could help with further development?

**Comment by kinke** [comment]
I'd also ask @smolt and @joakim-noah before merging this, as rebasing their presumably big ARM branches could easily turn out to be a nightmare.

**Comment by kinke** [comment]
They can reformat their current head, but not simply rebase their patches as nearly every source line would be formatted differently, or am I missing something?

**Comment by kinke** [comment]
Yeah, the approach of pre-comitting the re-formatted patches before merging the re-formatted master makes sense. I've never done it this way, but I'm also no git expert. ;)

**Pull request merged**
