### PR TITLE
dmd-testsuite: Enable GDB tests to see which ones still fail

### PR DESCRIPTION
**Pull request by kinke**
See https://github.com/ldc-developers/ldc/issues/1190.

### CODE REVIEW

**Comment by kinke** [comment]
I don't think so. All but one already worked (with gdb 7.11.1) if run manually outside dmd-testsuite, so we'd need to figure out why they fail as part of dmd-testsuite.

**Comment by rainers** [comment]
> Any change to this with your recent improvements?

I would not expect much. 

Trying to compile LDC on Ubuntu 16.04 with precompiled LLVM by just following the the steps in circleci.yml, I keep getting link errors with symbols containing std::string that have an additional abi tag cxx11 in the LLVM library. I'm probably hitting problems like http://stackoverflow.com/questions/36159238/linking-problems-due-to-symbols-with-abicxx11. Is there some way around that?

**Comment by rainers** [comment]
> link errors with symbols containing std::string that have an additional abi tag cxx11 in the LLVM library

It's the other way around.

> Is there some way around that?

Disabling the new abi works for me:
```
CC=clang CXX=clang++ cmake -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" .
```

**Comment by kinke** [comment]
Closing in favor of #1784.

**Pull request closed without merging**
