### PR TITLE
Try the new Travis docker environment

### PR DESCRIPTION
**Pull request by redstar**
Advantages: more CPU, more memory.
Disadvantages: currently not all LLVM versions are available

### CODE REVIEW

**Comment by redstar** [comment]
Read here: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
`sudo` is forbidden but you can download files and uses non-root folders to install.

I am also for dropping support for older LLVM releases.

**Comment by smolt** [comment]
Custom LLVM? does that open door for including TLS support for iOS?

**Comment by redstar** [comment]
@klickverbot  I think we can use the docker environment now. Current limitations:

 - I have not yet figured out the required packages for the multilib 32-bit build
 - LLVM 3.7 only as soon as the release is build
 - no LLVM snapshot builds

**Comment by redstar** [comment]
BTW I did not encounter a failure due to out of memory. :-) I also changed `-j2` to `-j3` because there are now 2 cores instead of 1.5.

**Comment by redstar** [comment]
I am still trying to get the best setup here. The hint with `linux-libc-dev:i386` was good. `libcurl` is still missing, too.

**Comment by redstar** [comment]
With `-j1` the OOM is gone.

**Comment by redstar** [comment]
Not yet perfect but the build times are good: LLVM 3.2 build is 16min for release only in old environment and 19min for release+debug in docker environment. For LLVM 3.3 it is 25min vs. 20min.

**Pull request merged**
