### PR TITLE
Merge v2.081.2

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
@joakim-noah: Please advance the submodule hashes here when cherry-picking druntime/Phobos stuff. For testing, but also visibility; where do the Phobos changes come from, and have they been reviewed?

**Comment by kinke** [comment]
Ah, cherry-pick of (merged) https://github.com/dlang/phobos/pull/6633.

**Comment by joakim-noah** [comment]
I usually don't bother updating the submodule hashes, because I figure somebody else will for their own commits eventually and I'm in no hurry. My stdlib changes are almost never tested by the ldc CI anyway, since they're for Android, ARM and AArch64. I only cherry-pick commits that've been approved upstream and tested locally, so shouldn't be a problem. If they're ldc-specific, I submit a pull here.

**Comment by kinke** [comment]
> I usually don't bother updating the submodule hashes, because I figure somebody else will for their own commits eventually

I know, 'cause it's almost always me. ;) Please do bother, as changes may get temporarily lost until someone else trying to branch off `ldc` (as opposed to just the latest submodule hash) eventually notices that things are out of sync. It's also helpful when generating the change log.

**Comment by joakim-noah** [comment]
Sure, will do.

**Pull request merged**
