### PR TITLE
AppVeyor: Publish a multilib CI build

### PR DESCRIPTION
**Pull request by kinke**
`get32BitArchVariant()` for x86_64 seems to return i386 which is inconsistent with i686 (Pentium Pro+) for a native 32-bit build.

### CODE REVIEW

**Comment by kinke** [comment]
Some PowerShell hacking for the AppVeyor multlilib build:
```PowerShell
If ($Env:APPVEYOR_JOB_CONFIG -eq 'Debug' -And $Env:APPVEYOR_JOB_ARCH -eq 'x86') {
    echo 'Preparing 32/64-bit multilib artifact...'
    cd c:\projects
    Start-FileDownload "https://github.com/ldc-developers/ldc/releases/download/LDC-Win64-master/LDC-master-$Env:APPVEYOR_BUILD_NUMBER-x64.7z" -FileName 'LDC-master-x64.7z'
    md ldc-multilib
    cd ldc-multilib
    7z x ..\LDC-master-x64.7z > $null
    ren lib lib64
    copy ..\ldc-x86\lib > $null
    ren lib lib32
    (gc etc\ldc2.conf).replace('%%ldcbinarypath%%/../lib', '%%ldcbinarypath%%/../lib64') | sc etc\ldc2.conf
    $conf32 = gc ..\ldc-x86\etc\ldc2.conf -Raw
    $conf32 = "`r`ni686-pc-windows-msvc:" + $conf32.Substring($conf32.IndexOf("`r`ndefault:") + 10)
    $conf32 = $conf32.Replace('%%ldcbinarypath%%/../lib', '%%ldcbinarypath%%/../lib32')
    ac etc\ldc2.conf $conf32
    $artifactFilename = "LDC-master-$Env:APPVEYOR_BUILD_NUMBER-multilib.7z"
    7z a "..\$artifactFilename" * > $null
    cd ..
    Push-AppveyorArtifact $artifactFilename
}
```

What needs to be sorted out is how to get the x64 artifact. The above would/should ;) only work if the commit is on the master branch and the Debug x64 job was successful (so that its artifact has already been uploaded to GitHub).

**Comment by kinke** [comment]
The 2nd commit can only be tested by merging this PR. ;)

**Comment by JohanEngelen** [comment]
@kinke Perhaps you can discuss with @redstar whether to add something like this to https://github.com/ldc-developers/ldc-scripts to help with releases?

**Comment by JohanEngelen** [comment]
> The above would/should ;) only work if the commit is on the master branch 

Does that mean that a PR would always fail testing?

**Comment by kinke** [comment]
> > The above would/should ;) only work if the commit is on the master branch 
> Does that mean that a PR would always fail testing?

In the preliminary version I posted here as comment, yes; but not in the 2nd commit, otherwise this PR would already fail because of it.

**Comment by JohanEngelen** [comment]
Ah, yes of course. 

LGTM.

**Comment by JohanEngelen** [comment]
( it does seem to make the AppVeyor build quite a bit slower (~15 mins?) )

**Comment by kinke** [comment]
Nope, the build is untouched, the multilib package is only generated when merging this PR. It's the dynamic AppVeyor VMs which show this inconsistent performance (sometimes, a VM doesn't even get a full physical core on its own...).

**Comment by JohanEngelen** [comment]
Great, so let's merge this.

**Comment by kinke** [comment]
Alright, I'm quite eager to see if it's working too. :)

**Comment by kinke** [comment]
It needed a lil' fix (https://github.com/ldc-developers/ldc/commit/bd3e1b210f4a3c6cfff6d5000c653d57eb2ef149) but should work now.

**Comment by kinke** [comment]
Okay so here's the first one: https://ci.appveyor.com/api/buildjobs/1ytgmu2d0in2qww1/artifacts/LDC-master-1641-multilib.7z
Works fine for me inside a naked cmd.exe instance (no VS environment variables set). It won't work inside a 'VS command prompt' as LDC doesn't attempt to find the VS installation and paths for the target architecture if the environment variables are already set.

**Comment by rainers** [comment]
Cool, works with Visual D, too! (I've tried my soon to be released local version only, though.)

**Pull request merged**
