### PR TITLE
Ios testing3

### PR DESCRIPTION
**Pull request by jacob-carlborg**
Just testing to see if making a new PR makes any difference with Bitrise.

### CODE REVIEW

**Comment by kinke** [comment]
I've pushed this (rebased) as `ios-testing3` branch on our repo, that seems to work. I've seen that the certificates are exposed to PR builds, so no idea what's missing. Maybe they still have a reference to your original repo and only expose it to PRs to your fork, not the new upstream repo here.

**Comment by jacob-carlborg** [comment]
> Maybe they still have a reference to your original repo and only expose it to PRs to your fork, not the new upstream repo here.

I don't see why that would be. I created a new project and exported the certificates again. I suspecting there's a bug in Bitrise with regard to this setting, that exposes the certificates to PRs.

I temporarily changed the URL for the repository to point to my fork and pushed directly to a branch in my fork. That worked.

Could please try and push this branch directly to LDC (I added dummy Xcode project to reduce the build times). This will hopefully determine if there's a bug in the Bitrise settings.

**Comment by kinke** [comment]
> Could please try and push this branch directly to LDC

I already did yesterday.

**Comment by jacob-carlborg** [comment]
> I already did yesterday (https://github.com/ldc-developers/ldc/tree/ios-testing3).

Ah, I see. Then it looks to me like there's a bug in Bitrise.

**Comment by kinke** [comment]
Still no good news?

**Comment by jacob-carlborg** [comment]
> Still no good news?

No, unfortunately not. I've reported the issue to the Bitrise support. I got the reply that they have escalated the issue to the technical support engineers for further investigation.

**Comment by jacob-carlborg** [comment]
> No, unfortunately not. I've reported the issue to the Bitrise support. I got the reply that they have escalated the issue to the technical support engineers for further investigation.

I've finally got an answer for the Bitrise support. Apparently exposing certificates to pull requests are not supported for public projects.

**Pull request closed without merging**
