### PR TITLE
GH Actions: Export ~all symbols from prebuilt LTO'd macOS binaries

### LINKED ISSUE #4462: macOS release package does not export all D symbols thus plugins do not work
This is probably related to cross building the package.

I'm testing now by applying `--export-dynamic` to any linker that supports it (so not only on UNIX but for all platforms).

### PR DESCRIPTION
**Pull request by kinke**
Fixes #4462 for our official packages.

### CODE REVIEW

**Comment by kinke** [comment]
@JohanEngelen: Please let me know if you want to pursue a generic LTO solution or whether that'd be good for now (modulo comments). I think fixing the exports on Mac is the only blocker for beta2.

**Comment by JohanEngelen** [comment]
I think this is OK for now. I guess there are not many people building with LTO anyway.
Can we leave a remark somewhere about the need for these extra flags with LTO ?

**Comment by kinke** [comment]
Feel free to add a further remark wherever you please if you didn't mean a YAML comment which I've just added. [I think the combo of using LTO, *and* needing plugin support, *and* on macOS is probably *really* rare. And I've quickly checked https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/ldc.rb, no LTO being used there.]

**Comment by JohanEngelen** [comment]
> [I think the combo of using LTO, _and_ needing plugin support, _and_ on macOS is probably _really_ rare.]

It does happen though :) Plugins are used at Weka, and people use the Github-built LDC on their macs. So thanks for the fix :)

**Pull request merged**
